### ISSUE TITLE
Desktop notification text is hard to read on a dark theme

### ISSUE THREAD

**Issue by derekjma** [inbasic/ignotifier#139]
When using a theme such as FT DeepDark, the desktop notification has black text on a dark background, which is nearly impossible to read.

Customizable notification text color would be nice.

**Comment by lasers** [comment]
What should I put in `userChrome.css` to remove dark background? Many thanks! 

![2016-09-19__05 06 30](https://cloud.githubusercontent.com/assets/852504/18628801/99bde256-7e27-11e6-9dd9-8aa914771e5b.png)

**Comment by inbasic** [comment]
@lasers what is the theme that you are using?

**Comment by lasers** [comment]
I'm using Firefox's builtin theme for Developer edition.  http://techdows.com/2015/01/firefox-35-how-to-enable-developer-editions-dark-theme.html

You also can use this extension. https://addons.mozilla.org/en-US/firefox/addon/devedition-theme-enabler/

**Comment by inbasic** [comment]
Please try the latest dev version and let me know if the issue is fixed or not;
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

download the XPI and then open about:debugging in a browser tab. Enable developer mode and point the browse button to the downloaded XPI

**Comment by inbasic** [comment]
Unfortunately, I am not able to reproduce it. Please give https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true a try and let me know if the bottom line color is fixed or not. Is this black line visible in the full mode too?

**Comment by lasers** [comment]
The line was there for full mode too. This new xpi is absolutely perfect now. I tested the old xpi again to see if it would bring the line back. It did. Many thanks for this newly founded extension. :-)

**Comment by inbasic** [comment]
can you share an screenshot. The problem is I don't want to force the white color on different elements as it might overwrite the CSS rules.

**Comment by lasers** [comment]
![2016-09-21__09 43 09__github](https://cloud.githubusercontent.com/assets/852504/18716192/85957fbc-7fe1-11e6-95f8-04f8afdf7cce.png)

**Comment by inbasic** [comment]
Are you sure you **only** have the dev theme? Can you confirm this by creating a fresh profile and trying out GN there with dev theme enabled? http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

I can fix the background color issue of these elements but there is a chance this overwrites the defaults and some emails wouldn't be displayed correctly under the normal theme.

**Comment by lasers** [comment]
Sorry! Gmail Notifier works flawlessly in dev theme in a fresh profile. I had other themes too. Arc{,-Dark{,er}} (disabled). That wasn't the problem but it helped a lot with troubleshooting.

Thank you for helping me with this. From there, I disable userscripts and extensions one at a time... right down to vimperator. There was a style code overriding background color for about:blank and about:newtab in the ~/.vimperatorrc. I don't remember putting them in there myself so it was likely something else I toggled or installed... and later update the config file with new options.

To others: If you're having color issues, try it with a fresh profile first to rule out all userscripts and extensions before you bother this nice developer! 👍
