### ISSUE TITLE
[Feature Request] Add option to change/add label/s

### ISSUE THREAD

**Issue by simonbcn** [inbasic/ignotifier#178]
Add option to change/add GMail label/s in preview panel.
Thanks.

**Comment by federomano** [comment]
+1 on this proposal!

**Comment by nanofino** [comment]
+1, I really need it :D

**Comment by sojusnik** [comment]
+signed

**Comment by inbasic** [comment]
labels are now being shown and they can be removed from the popup UI. Adding labels needs more work. If anybody is interested please open a pull request.
