### ISSUE TITLE
0.4.5b4: HTML image links broken

### ISSUE THREAD

**Issue by trlkly** [inbasic/ignotifier#220]
Image links are not working in any of my emails. Hovering over them shows their URL in the status bar, but clicking (left, middle or right) does nothing. 

Text links still work fine, as does highlighting and copying text with the right mouse button. Only linked images seem to not work.

**Comment by trlkly** [comment]
This seems to be broken again. Clicking an image link takes me to the image, rather than following the link. 

To quote from above:
>when it sees `<a href="htttp://example.com"><img src="example.jpg"></a>`, clicking on the image takes me to example.jpg, not example.com.

**Comment by inbasic** [comment]
@trlkly, Is this duplicate of https://github.com/inbasic/ignotifier/issues/426?

**Comment by trlkly** [comment]
Yes, it seems to be. The fix there seems to have fixed the issue. I didn't think to search closed issues. 

How long before the dev version is signed and published to AMO?
