### ISSUE TITLE
Not getting proper feeds from primary category

### ISSUE THREAD

**Issue by arminus** [inbasic/ignotifier#241]
Hi,

I understand that https://mail.google.com/mail/u/0/feed/atom/^smartlabel_personal should correspond to the contents of the Primary category in the inbox, right? Unfortunately, the mails I get via that RSS feed are different from the ones I see in the GMail interface in the Primary tab in the inbox?

thx!

**Comment by pkgh** [comment]
I'm not really so good at scripting. Could you, or anyone, put together a template for trying?

**Comment by inbasic** [comment]
there are new smart labels. You can use them. Read the FAQs page for more info
