### ISSUE TITLE
Notifier shouldn't execute upon marking email as unread

### ISSUE THREAD

**Issue by LGFN** [inbasic/ignotifier#257]
Every time I mark an email as unread the notifier sounds and pops up, making me believe that a new email arrived. The notifier shouldn't appear when an email is marked as unread, in my humble opinion.

**Comment by inbasic** [comment]
Thanks for the report. The new dev version only notifies for incoming emails arrived within 10 minutes period. This value can be changed from settings page though.

You can try this dev version now
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download the XPI file and drop it into your Firefox browser.
