### ISSUE TITLE
feature request: per-label audio

### ISSUE THREAD

**Issue by meoso** [inbasic/ignotifier#277]
looking forward to possibly having different audio for different labels.

**Comment by inbasic** [comment]
The new version will allow you to define filters for sound notifications;

You can try the beta version now:
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true
Download the XPI and load it in about:Debugging tab

**Comment by meoso** [comment]
well, i certainly appreciate it and don't want to be negative in any way; however, from what i see this is not the same as a label based notification.  i have slightly complex label filtering.  i think a fourth drop-down = "label" would be necessary for me.  name, email, title, & content don't really work as a replacement for my complex label-filtering which has already been "worked out" and trying to establish the same with this method seems futile. thank you for your continued support!

**Comment by inbasic** [comment]
So do you need filters for those labels defined in the settings page (check unread emails only for these labels instead of inbox) or the labels Gmail attaches to incoming emails based on the filters you define in the Gmail's settings page? The notifier has no access to the latter one and having a matching trigger for the former doesn't seem to be that useful.

**Comment by meoso** [comment]
The second (labels Gmail attaches to incoming emails based on the filters I define)
Essentially, i would want the following:
Nofication 1 (/mail/u/0/) "IT_Staff" = "zing.wav"
Nofication 2 (/mail/u/0/) "SAN_Alarm" = "alert.wav"
Nofication 3 (/mail/u/0/) "VM_Alarm" = "warp.wav"
Nofication 4 (/mail/u/0/) "Veeam_Alarm" = "bong.wav"
etc.

**Comment by inbasic** [comment]
Sorry this is not possible until https://github.com/inbasic/ignotifier/issues/178 is implemented. Currently GN only fetches RSS feeds and Gmail's feed does not provide label's info.
