### ISSUE TITLE
Chrome : Manual refresh from the icon

### ISSUE THREAD

**Issue by pkgh** [inbasic/ignotifier#280]
I'd love to have the option to manually refresh, sort of like Ctrl+Click on Firefox. This way I can be free from automatic notifications if I choose so (after setting a long interval in the settings). Right now manual refresh is only possible with the loaded pop-up (i.e. with at least 1 unread email reported). Thanks for this great extension and for any consideration you can give to my request. Happy New Year :)

**Comment by inbasic** [comment]
Unfortunetly, in Chrome, there is no way to catch these events. Extension only receives click event, not even right or middle clicks are catchable.

**Comment by pkgh** [comment]
Thanks.
How about a two-click solution?
E.g. an additional setting option like "Show toolbar rather than gmail"
even when currently reported number of unread emails is zero? The toolbar
popup would then show the refresh button ..
Or else a right-click manual refresh option? Might be slicker. I think
Chrome does allow right clicks on extension icons - e.g. AdBlock shows me
some of its blocking options when I right-click..
Happy New Year :)

**Comment by Nekomajin42** [comment]
The AdGuard extension has a custom context menu too.

**Comment by inbasic** [comment]
> Chrome does allow right clicks on extension icons - e.g. AdBlock shows me some of its blocking options when I right-click..
@pkgh I don't see any custom item in Adblock Plus's right click menu
![screen shot 2015-02-09 at 11 37 46](https://cloud.githubusercontent.com/assets/351062/6102692/46f10d4c-b050-11e4-9069-9d400159ecd5.png)

**Comment by pkgh** [comment]
Sorry, I meant Adblock not Adblock Plus, and I see this:
![2015-02-09 11_18_44 - chrome legacy window_chrome _ manual refresh from the icon issue 280 inbasic_ignotifier - google chrome](https://cloud.githubusercontent.com/assets/6607293/6104431/bb40e9b8-b04d-11e4-967f-805fff5becca.png)

**Comment by inbasic** [comment]
I see! I was on Mac and it turned out custom context menu items are not yet activated there. 
In version 0.5.3 we have two new items 
![screen shot 2015-02-09 at 19 45 54](https://cloud.githubusercontent.com/assets/351062/6110941/8c0c230e-b09a-11e4-9a4c-484b9ed2fe7b.png)

> This way I can be free from automatic notifications if I choose so (after setting a long interval in the settings)

No need to set a long interval, just set the value to zero as mentioned in the description.

You should receive the update within an hour of this post.

**Comment by pkgh** [comment]
The new options are great, thanks! Regarding where to put "0" though:

"Check for new emails every" comes with "Minimum period is 10 seconds." warning, so not sure I can use zero there.

"Do not check for new emails on startup for"  - here zero allowed but the behavious is described as "Set the value to zero for no email check until the first manual refresh [Not available on Safari]."

So, if I want a permanent setting of "don't bother me, I will refresh manually", what are the recommended options?

Many thanks!

**Comment by Nekomajin42** [comment]
Will it work in Opera too?

**Comment by inbasic** [comment]
@pkgh I see. So basically there is no option for this at the moment. We can have a new option for this if the method you suggested is not working well. So try yours, if not satisfied, then open a new bug.

@Nekomajin42 I really doubt if it works on Opera. However, I am on Mac, and it might work in the windows version as of Chrome case. You can simply try it yourself by enabling the developer mode. Then head to the Chrome web store and download the Chrome version.

**Comment by pkgh** [comment]
Thanks for the reply. No need for a new option - I can specify a very long interval and that's OK with me. Thanks!

**Comment by Nekomajin42** [comment]
@inbasic
It works. At least in the newest dev build. Would you test it and update in the Opera addon catalog?

**Comment by inbasic** [comment]
@Nekomajin42, version 0.5.3 has been submitted to opera for review. Hopefully it will be available soon.

**Comment by Nekomajin42** [comment]
It is available now. Thanks!
