### ISSUE TITLE
After latest update checking for unread messages under all labels stop to work.

### ISSUE THREAD

**Issue by blacklion** [inbasic/ignotifier#281]
Way to check all labels in one was give in issue #148. It worked well, but stop to work with latest update, when structure of configuratio was changed.

If I set "label" to "feed/atom/unread" (to get full URL from #148) extension stops to check even inbox.

**Comment by inbasic** [comment]
how about `unread` label?

**Comment by blacklion** [comment]
It works!

**Comment by inbasic** [comment]
Great!

**Comment by blacklion** [comment]
Last update lost this setting. Thanks to github issue seacrch, I could find this receipt again. But it was surprise to me to miss several e-mails for several hours (I don't have a lot un-filtered email in Inbox).
