### ISSUE TITLE
Multiple account not woking in linux

### ISSUE THREAD

**Issue by baivong** [inbasic/ignotifier#282]
I'm used:
* Linux Mint 17.1 cinnamon
* Firefox 34.0.5-SSL linux64

I opened three gmail accounts but Gmail Notifier just received the first account.

**Comment by inbasic** [comment]
Open the Options, in the feeds section make sure all accounts have `inbox` label

**Comment by baivong** [comment]
It worked. Thank you, this is a great add-on.
