### ISSUE TITLE
Firefox 34 / Gnotifier 0.5.1 -  doesn't recognize additional gmail accts

### ISSUE THREAD

**Issue by mad4max** [inbasic/ignotifier#283]
I have followed your instructions precisely:
How to sign-in into multiple accounts at once?
First, sign-in to your primary Gmail account. Then click on your name or email address at the top of the page. Select "Add account" from the drop-down menu. On the page that opens, enter the email address and password for another account you wish to access, and click "Sign in".

Gnotifier only recognizes my primary account..

Your next question will be "what is your gmail feed settings"

currently, they are all blank. I have tried different permutations, with no success. frankly, i find this section of the options page completely incomprehensible. I have no idea what to put in the text boxes.

i have tried putting in my email addresses (with and without acct id, /mail/u/x)

I am using checker plus for gmail in chrome & it recognizes all 3 accounts with no issues

please advise

thank you

**Comment by chiherka** [comment]
Hi 
I have got exactly the same problem on Opera 26.0

**Comment by inbasic** [comment]
Go to the Options, and make sure in the feeds section you have label `inbox` for all accounts.
