### ISSUE TITLE
Issue accessing my email accounts on Firefox v.35

### ISSUE THREAD

**Issue by petros734** [inbasic/ignotifier#284]
Hi,
by pushing the gmail notifier icon, I get a screen withthe following message:

" The page does not redirect correctly

Exceeded redirection limit for this URL. Loading stopped.

     This problem can be derived from disabling or refusing cookies."

Any suggestions ?

**Comment by inbasic** [comment]
Can you confirm on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
