### ISSUE TITLE
Blank window

### ISSUE THREAD

**Issue by justanotheranonymoususer** [inbasic/ignotifier#286]
Sometimes what I get is a blank window, and the only solution is to restart the addon.
Unfortunately, I don't know how to reproduce the issue, but it happened more than once to me.

Screenshot:
![asdf](http://i.snag.gy/oNJ4K.jpg)

**Comment by inbasic** [comment]
This most probably is Firefox bug, not GMN bug. If it occurs a lot try to migrate to a new profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
