### ISSUE TITLE
Cannot add more than 1 account and options not working.

### ISSUE THREAD

**Issue by JohnnyGaloshes** [inbasic/ignotifier#288]
Recently i have noticed that i cannot add more than one account at a time to monitor. Also i click Options and the screen freezes. I can't click on anything else and no window pops up. Need to do window close from task manager. Firefox is current and updated. Was doing it before update also.

**Comment by inbasic** [comment]
To open options, right click on the toolbar button and select Options. Make sure all accounts under feeds section have label "inbox".

**Comment by JohnnyGaloshes** [comment]
Thanks for the reply. If i right click on firefox toolbar no selection for "Option" will present itself. But, if i go to the options selection and go to firefox options i don't see anything pertaining to "feeds section"

Am i looking in the wrong place?

**Comment by inbasic** [comment]
You need to right click on the toolbar button itself. If you prefer options button in the addon manager, then download version 0.5.2b1 first,
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions
