### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by pvlb** [inbasic/ignotifier#291]
1. stopped working on Chromium 42.0.2300.0 (64-bit for linux) :(
2. need buttons: "Compose on email" and "Send link"
3. need to be able to zoom in the message body (text) for Chromoium/Firefox

**Comment by inbasic** [comment]
1. It is working fine for me! Try logging out from Gmail once.
2. To reply to current email, just click on the sender's name in the panel. "Send Link" is not available though.
3. I am not sure if I got your point
