### ISSUE TITLE
Feature request: less intrusive mode for desktop notifications

### ISSUE THREAD

**Issue by klint** [inbasic/ignotifier#293]
Hello
I'm using this excellent addon at work, and I find the desktop notifications very handy but too intrusive visually speaking ;)
Could there be an option to both remove the icon and the name of the addon in the notification, and keep text pieces from the mail only? :)
Thanks

**Comment by inbasic** [comment]
Icon and name are mandatory. For the rest you can customize the notifications from options -> "Notification" section.
