### ISSUE TITLE
Multiple account doesn't work anymore

### ISSUE THREAD

**Issue by maynaleen** [inbasic/ignotifier#294]
I used to use Gmail Notifier for 4 gmail accounts.
But yesterday I reset my Firefox and re-install the add-on, and now the multiple account doesn't work anymore. It shows only my default account.
I tried to re-install the add-on and re-log in the gmail accounts but it doesn't help.

Please help me. Thank you.

**Comment by inbasic** [comment]
Go to the settings and make sure all accounts on the `feeds` section have label `inbox` in their fields

**Comment by maynaleen** [comment]
It works like magic! Thank you very much!

**Comment by Allasso** [comment]
I have updated to 0.5.2.1 to correct options no opening.  All accounts have `inbox` in their field.  However, the only account I receive notification for is the account which I am currently logged into.

**Comment by inbasic** [comment]
@Allasso isn't this the expected behavior?  The notifier can only notify you about those accounts that are already logged-in.

See FAQ 5, http://add0n.com/gmail-notifier.html

**Comment by Allasso** [comment]
I am confused, as I am unable to log into more than one account at a time, or am I?  ie, AFAICT, in order to log into another account, I have to sign out of the other.  Isn't this how cookies work?

**Comment by inbasic** [comment]
@Allasso yes! read FAQ 2 for the instruction.

**Comment by Allasso** [comment]
Okay, thanks, I use "HTML View", and had to switch to "Standard View" to see that.  Works now.
