### ISSUE TITLE
Unable to access preferences/options/settings

### ISSUE THREAD

**Issue by Allasso** [inbasic/ignotifier#295]
I am unable to access preferences/options/settings from the "preferences" button for this addon in about:addons page.  I also do not find another way to access preferences.

Using Firefox 34.0.5 : Mac OS X 10.9

**Comment by inbasic** [comment]
Try version 0.5.2.1
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions/

**Comment by Allasso** [comment]
That worked, thank you.
