### ISSUE TITLE
Oversized toolbar button in 0.5.2.1

### ISSUE THREAD

**Issue by tombones** [inbasic/ignotifier#297]
Just updated to the latest version for Firefox 36, and unfortunately it appears the toolbar button is now being stretched out for some reason. I'm using small icons and the default firefox theme. Screenshot of the issue: 
![image 296](https://cloud.githubusercontent.com/assets/3936058/6364811/2f81d994-bc7a-11e4-9ffe-0b985e15821a.png)

The addon is working as well as it ever has (wonderfully!) otherwise.

Please let me know if you need any further info.

Thanks!

**Comment by inbasic** [comment]
It seems more like a theme issue. Do you have the same problem on the default theme?

**Comment by tombones** [comment]
This is the default theme. I have a skin on, but that doesn't change the
theme. The problem persists with the unskinned, default theme:


​

**Comment by inbasic** [comment]
That's weird! It looks just fine in my FF 36.0. 
Have you tried moving the button once to the customize palette and then moving it back to the toolbar?

If it didn't work, please try extension on a clean profile as well,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by tombones** [comment]
it's looking like this is probably related to a Classic Theme Restorer
update. I'm going to just use a different theme for now and hope that they
fix it.
