### ISSUE TITLE
Can not detect the second gmail account.

### ISSUE THREAD

**Issue by Russell-Huang** [inbasic/ignotifier#300]
The newest version(0.5.2.1) can not detect the second gmail account.

I already try Read FAQ 5, but not work.
I make sure both two account are login, and have inbox and can used.
![2015-02-26_175547](https://cloud.githubusercontent.com/assets/11209703/6389756/e211016c-bde1-11e4-8e34-e7a3749de2b9.jpg)
![2015-02-26_175613](https://cloud.githubusercontent.com/assets/11209703/6389757/e218c65e-bde1-11e4-924e-49dac78b0e1c.jpg)

And I also can't reset default at this version.

**Comment by inbasic** [comment]
Do not use the custom feeds section. Instead insert label `inbox` in all "... account (/mail/u/..../)" text boxes.

**Comment by inbasic** [comment]
Just for reference if you prefer the custom feeds section, the format is as follows:
```
https://mail.google.com/mail/u/0/feed/atom,https://mail.google.com/mail/u/1/feed/atom
```
