### ISSUE TITLE
Hungarian back to English

### ISSUE THREAD

**Issue by KissDaniGH** [inbasic/ignotifier#301]
hi
just upgraded and hungrian strings went back to english.
And only the 1st account is regonized by default, I had to write "inbox" into gmail/primary and secondary input boxes to get notifications about incoming mail to my 2nd account.

regards, Daniel

**Comment by inbasic** [comment]
Sorry about the Hungarian translation. I need to update my compiler to support language files. 

 > And only the 1st account is regonized by default, I had to write "inbox" into gmail/primary and secondary input boxes to get notifications about incoming mail to my 2nd account.

In a clean profile, I guess it detects all accounts by default even when there is no label `inbox` in the boxes. I am not sure why it is not the case for old profiles. I'll investigate.

**Comment by inbasic** [comment]
Let's take care of all translation issues here
https://www.transifex.com/projects/p/gmail-notifier-addon/

Would you mind updating yours too?
