### ISSUE TITLE
Wakes Up Monitor

### ISSUE THREAD

**Issue by pvangelder573** [inbasic/ignotifier#308]
My laptop's power setting turns my display off after 30 minutes of inactivity. Any new Gmail after that happens will wake my display back up with this extension installed. Is there a setting that can be changed or is this a known issue? This add-on is exactly what I was looking for except this isn't what I want because I keep my laptop right next to my bed.

**Comment by inbasic** [comment]
Is this helpful,
https://github.com/inbasic/ignotifier/issues/246

**Comment by pvangelder573** [comment]
After more playing around with the settings yesterday after I posted, I found that the only way for it to keep it from waking up my display is to have both the sound notification turn off and to have the option for always having the notification icon in the system tray turned on. As long as both of these options are set this way, the screen does not turn on when I receive an email. Thanks for your reply.
