### ISSUE TITLE
Use new Firefox badged button API

### ISSUE THREAD

**Issue by Klaster1** [inbasic/ignotifier#309]
Firefox 36 got [new API for badged buttons](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action), how about using it? All extensions that display numbers in panel should really look the same.

**Comment by inbasic** [comment]
Try the latest beta version, https://addons.mozilla.org/en-US/developers/addon/gmail-notifier-restartless/versions

**Comment by Klaster1** [comment]
Thanks, I like it much better now, but the badge seems to be slightly misaligned vertically:
![badges](https://cloud.githubusercontent.com/assets/2667662/6641345/c4ac28dc-c9cf-11e4-960e-a5fbdd0fbcb6.png)

**Comment by inbasic** [comment]
Are you sure the other addon uses 16px icon? Please confirm with a third addon with badge notification.

**Comment by Klaster1** [comment]
Good question. To test this I've made my own extension that uses 64x64 icon and checked additional styles for conflicts, but ignotifier is still lover than the other two:
![badges-2](https://cloud.githubusercontent.com/assets/2667662/6652076/d31c335c-ca93-11e4-8d1c-0325892e030e.png)

**Comment by inbasic** [comment]
Have you tried 16px icon instead of 64px?

**Comment by Klaster1** [comment]
No, I did not. If you think this might be the issue, I will, but a bit
later.

2015-03-14 21:53 GMT+07:00 InBasic <notifications@github.com>:

**Comment by inbasic** [comment]
Yes, we use the recommended 16x16 icon. If an extension uses a different icon size, the badge could have been misplaced.

**Comment by Klaster1** [comment]
>recommended 16x16 

Can you provide a reference? The only thing related to button icon sizes I was able to find is [this page](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_toggle#ToggleButton%28options%29), which says you are free to use any size and Firefox will choose the most suitable, this final form being stack of [18,32,36,64].

Here's a comparison between 16px (top) and 18px (bottom) icons, only "M" button was affected:
![badges-3](https://cloud.githubusercontent.com/assets/2667662/6652424/9e7b3de8-caa0-11e4-83de-8ec02ab64ef2.png)

Screenshot was taken in fresh v38 developer profile.

I guess the problem is caused by imperfect XUL CSS.

**Comment by inbasic** [comment]
So as you can see if you use 16px icon, your badge is aligned with GN's, and if you use 18px, the badge is aligned with the other extension's. We still prefer to use 16px icon though for compatibility purposes with the older versions of Firefox.
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Toolbars/Creating_toolbar_buttons

> I guess the problem is caused by imperfect XUL CSS

Don't think so. If you want to test, just fork GN and change the icon size to 18px and recompile. You will see all the three badges will align.

**Comment by lililya** [comment]
In my point of view and I'm used to this production. My computer is limited, it is nothing, only 70G hard drive. Understanding it.


lililya521@outlook.com
 
From: InBasic
Date: 2015-03-14 22:53
To: inbasic/ignotifier
Subject: Re: [ignotifier] Use new Firefox badged button API (#309)
Have you tried 16px icon instead of 64px?
