### ISSUE TITLE
Sounds Not Working

### ISSUE THREAD

**Issue by Spidersouris** [inbasic/ignotifier#310]
Hello!

Since two weeks, my notifications sounds doesn't work. I tested with the default sound or even a custom sound, but nothing.

I'm on Firefox Nightly 39.0a1.

Thanks for your help!

Best regards,

**Comment by inbasic** [comment]
Can you confirm the problem on a clean profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Spidersouris** [comment]
Yea, same problem.

Plus, after some minutes, the mail button becomes blue for no reason. In my preferences, it must be blue when disconnected and grey when I have no mail, but my gmail account is never disconnected, so I don't understand...

Thanks for you help.

**Comment by inbasic** [comment]
Is it going back to red/gray after a while or it stays blue?

**Comment by Spidersouris** [comment]
'k, found the problem for the mail button : when I open Firefox, the button is blue, and I must right click and "Refresh" to make it red/gray. I'ts ok, I'ts not a huge problem.
But I didn't have found the problem for the sound.

**Comment by inbasic** [comment]
You must have changed a setting, go to the addon option page and look for,
`Do not check for new emails on startup for ...`
Make sure the number is not zero.

**Comment by Spidersouris** [comment]
Oh, yeah I'm sorry, it was that...

And for the sound problem?

**Comment by inbasic** [comment]
I have no idea! If you want to reset all the settings you need to install the extension on a clean profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
