### ISSUE TITLE
Quoted text hidden

### ISSUE THREAD

**Issue by zeird** [inbasic/ignotifier#311]
![](http://i.imgur.com/zLBTLQA.png)
A link to the topic is in the quoted text, which is hidden. So I must open GMail, then open the message, then open quoted text and then I can get to a topic. That's too much effort. Can you do something with it?

**Comment by inbasic** [comment]
Quoted text is now linked to the topic in the latest beta version,
https://addons.mozilla.org/firefox/downloads/file/306026/gmail_notifier_restartless-0.5.3b6-fx.xpi?src=devhub

**Comment by zeird** [comment]
It's not quite what I wanted.
Is it possible to just _show_ hidden quoted text when clicking the "Quoted text hidden" instead of opening it in GMail? I guess that should be possible because in summary mode it shows a part of the quoted text at least.
![](http://i.imgur.com/uT1HuiV.png)

**Comment by inbasic** [comment]
No it is not possible at the moment. GN can only get the content of current email, not the thread. I am working on a fix though.

**Comment by zeird** [comment]
I got it. GN requests print version of messages, and gmail responses with that notorious "[Quoted text hidden]".
I've found a workaround though: I disabled conversation mode in gmail settings and now GN shows full messages. That's fine with me, because in this case I'll never have to open gmail (except for composing new messages or for searching for old ones, what happen on rare occasions).
Thank you very much for the efforts and for great add-on!

**Comment by zeird** [comment]
I made a little research. Check out what I've learned:

---

1. When ```Conversation view``` in ```GMail settings``` is ```on```, printing versions of messages are shown cut (with ```[Quoted text hidden]```).
2. When ```Conversation view``` is ```off```, printing versions of messages are shown entirely (without ```[Quoted text hidden]```), but there are issues with ```Atom Feed``` showing unread messages disregarding actual ```Conversation view``` setting, like it's is always ```on```.

---

So my proposal to you is to implement the following algorithm:
1. Disable ```Conversation view```.
2. Fetch uncut messages bodies.
3. And then enable ```Conversation view``` back.

---

To disable ```Conversation view``` the one should send GET-request:

    https://mail.google.com/mail/u/0/?ik=actual_ik&at=actual_at&view=up&act=prefs&p_bx_vmb=1

where ```actual_ik``` is the ```ik``` returned by your ```GetIK``` function, ```actual_at``` is action token returned by your ```getAt``` or ```getAt_2``` function, I don't know for sure, ```view=up``` prevents redirection to gmail page, ```act=prefs``` changes preferences and ```p_bx_vmb=1``` is the parameter that actually disables ```Conversation view```. I stripped all redundant parameters from the request, these 5 are the minimum needed.

---

To enable ```Conversation view``` back the one should send similar GET-request:

    https://mail.google.com/mail/u/0/?ik=actual_ik&at=actual_at&view=up&act=prefs&p_bx_vmb=0

but with ```p_bx_vmb=0```.

---

Those requests should return empty response, but you can add ```&rt=c``` and it'll return ~2KB with text "Your preferences have been saved.". I tested that two GET-requests on Firefox and Chrome. Works in both browsers.

I gave you all the info. So, the question is: could you please implement this? :octocat:

**Comment by zeird** [comment]
And it may need to add ```&ik=actual_ik&ui=2``` to requests in ```sendCmd``` function in order to work with "conversation mode off"-messages.

**Comment by inbasic** [comment]
well instead of changing the Conversation view on and off I would say it is better to get the printed view of entire thread instead of just a message,
![screen shot 2015-03-30 at 10 53 00](https://cloud.githubusercontent.com/assets/351062/6891043/35f19970-d6cb-11e4-8628-634629cc1ea1.png)
The only problem is we need the thread id (`th`) and we don't have it in the feed's response,
https://mail.google.com/mail/u/0/feed/atom

**Comment by zeird** [comment]
I'm afraid that's not the only problem. Even if you'll manage to get ```th``` somehow, it won't work.
I opened a random conversation thread (see [this screenshot](http://i.imgur.com/aOoCcu1.png), which is pretty big to just embed it) and discovered that quoted text is shown only for the oldest message of a thread while for other it's still hidden. And the real problem is that you don't know what quoted text is for sure and there's no way to calculate it. You can't just copy if from the first message, or combine old messages, because quoted text is basically anything following ```---```.

**Comment by inbasic** [comment]
right, is this fixed now?
https://addons.mozilla.org/firefox/downloads/file/306482/gmail_notifier_restartless-0.5.3b7-fx.xpi?src=devhub

**Comment by zeird** [comment]
Oh wow! It's fixed now. You're a genius! Who knew it would be that simple? Good work. Now I'm happy.

**Comment by inbasic** [comment]
Perfect and thanks for the bug report.
