### ISSUE TITLE
Preview panel is not localized

### ISSUE THREAD

**Issue by KissDaniGH** [inbasic/ignotifier#312]
Hi
everything seem perfect, but preview panel is still english:
1 of 1
2 minutes ago / Jut now
tooltips
Thanks the hard work ;)
Daniel

**Comment by inbasic** [comment]
Thanks for the confirmation. Yes, for panel to be localized I need to figure out how to localize the tooltip strings first. It is not happening till our next release though.

**Comment by odie2** [comment]
@inbasic 
As I see phrases are in [popup/index.js](https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/data/popup/index.js).

Have you tried following for JavaScript?
* https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/l10n#Using_Localized_Strings_in_JavaScript
* https://developer.chrome.com/extensions/i18n
* http://stackoverflow.com/a/14359147/2491556

**Comment by inbasic** [comment]
well the problem with the panel is those tooltip shown for action buttons. Not the translation, but the alignment. I need to find a better way to implement these tooltips first.

**Comment by inbasic** [comment]
with https://github.com/inbasic/ignotifier/commit/827a424a3c009c0f7970da64fba6b660ac3590de it is now possible to localize the panel window. Please update your locales to see if localization still needs improvements.

**Comment by odie2** [comment]
Awesome.

However, this time I have problem with installing extension directly from directory in Opera, it results in
![image](https://cloud.githubusercontent.com/assets/9401878/11613046/15cb9ad4-9c13-11e5-8229-5644af6edca5.png)

Moreover, I can't see extension directory by ID in `AppData\Roaming\Opera Software\Opera Developer\Extensions` even after restarting browser.

I tried `src` directory from **master** and **multi-browser** branch, as before it was working.

Any advices?

**Comment by odie2** [comment]
Ok, `chrome.zip` archive from `builds/packed` seems like working.

**Comment by inbasic** [comment]
Right! I still haven't updated the `ReadMe.md` file. I've recently switched to [http://gulpjs.com/](http://gulpjs.com/) compiler to automate package creation. So from now on only the files in the `builds` directory are the correct executables.

**Comment by odie2** [comment]
![image](https://cloud.githubusercontent.com/assets/9401878/11613128/0e875698-9c16-11e5-8773-e3ad59ae066b.png)

* `<b>-</b> <span data-l10n-id="popup_of"></span> dd<b>-</b>` in `data\popup\index.html`
* Mark as read is not translated (perhaps line 350 in `data\popup\index.js` - `qs('read').textContent = "Mark as read";` and line 474 - `qs('read').textContent = "Mark as read";`)
* Missed phrase - line 320 in `data\popup\index.js` - `qs('read').textContent = "Wait...";`

**Comment by odie2** [comment]
* "me" is not translated

![image](https://cloud.githubusercontent.com/assets/9401878/11613164/7222d172-9c17-11e5-9bb0-b60fe7edc684.png)

**Comment by odie2** [comment]
* missed "(no subject)" phrase, line 129 in `data\popup\index.js` - `title.textContent = val  || "(no subject)";`

![image](https://cloud.githubusercontent.com/assets/9401878/11613167/a09e4fa4-9c17-11e5-82e9-d19a852973f2.png)

**Comment by inbasic** [comment]
> "me" is not translated

Thanks! All these issues are fixed except the "me" one. Actually the me is returned by Gmail's feed, https://mail.google.com/mail/u/0/feed/atomhttps://mail.google.com/mail/u/0/feed/atom. I am not sure if it would be possible to get the localized feed.

https://github.com/inbasic/ignotifier/tree/master/builds/packed

**Comment by odie2** [comment]
What about modifing
```
set name(val) {
   name.textContent = val;
},
```
(lines 120-122 / 117-119 in .js)

to something like this?
```
set name(val) {
   if ( val == "me" ) { val = [translation here]; }
   name.textContent = val;
},
```
?

I think there is just 0,(0)1% chance to sender may be named "me" :v

**Comment by inbasic** [comment]
I'll try to find the localized feed first; if there wasn't any then this is our best bet.

**Comment by odie2** [comment]
It would be useful to have plural forms for time, because without it I could do
```
2 tygodni(e) meaning 2 tygodnie
5 tygodni(e) meaning 5 tygodni
```
but there is a problem:
```
2 miesiąc(e) meaning 2 miesiące
5 ??? meaning 5 miesięcy
```

Maybe there is something already builded in `manifest.json` to do like this.

Generally this works in one way:

**.po file**
```
msgid "%d directory"
msgid_plural "%d directories"
msgstr[0] "%d katalog"
msgstr[1] "%d katalogi"
msgstr[2] "%d katalogów"
```

**system for C language in GitExtensions**:
`{0} {1:miesiąc|miesiące|miesięcy} temu`

 It's the most common pattern (`nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);`), meaning:
```
first form = 1
second form = 2, 3, 4, 22...
third form = 0, 5, 6, 7...
```

---

It also would be nice to have possibility to translate line 572
(`][date.getMonth()] + " " + date.getDate() + ", " + date.getFullYear().toString();`)
for custom date format.

I have now a little grammar problem with it for month name, but I will deal with it if I could write custom date format.

**Comment by inbasic** [comment]
I see. Seems like localization is not that powerful in Chrome extensions, https://www.chromium.org/developers/design-documents/extensions/how-the-extension-system-works/i18n#TOC-Plural-form
Firefox is better though https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/l10n#Plurals

Anyhow, I have moved a few more formatting options to the `messages.json` file.
https://github.com/inbasic/ignotifier/blob/master/src/_locales/en/messages.json#L386
https://github.com/inbasic/ignotifier/blob/master/src/_locales/en/messages.json#L434
https://github.com/inbasic/ignotifier/blob/master/src/_locales/en/messages.json#L440
