### ISSUE TITLE
Translation of description

### ISSUE THREAD

**Issue by odie2** [inbasic/ignotifier#313]
For Opera addons page - `https://addons.opera.com/en/extensions/details/gmail-notifier/?display=[2-char language code]`

For Polish - https://addons.opera.com/en/extensions/details/gmail-notifier/?display=pl

```
Powiadomienia Gmail to projekt otwartego oprogramowania, który powiadamia o przychodzących wiadomościach ze wszystkich Twoich etykiet z kont Poczty Google.

Cechy:
1. Brak wymogu wprowadzenia danych.
2. Obsługa wielu kont.
3. Obsługa wielu etykiet.
4. Małe zużycie przepustowości łącza dzięki technologii RSS.
5. Oznacz jako przeczytane, zgłoś spam, usuń lub przenieś do archiwum z poziomu paska narzędzi Opera.

Uzyskaj więcej wskazówek o używaniu rozszerzenia na stronach pomocy:
1. Jak zalogować się jednocześnie do kilku kont?
2. Jak uzyskać powiadomienia z danej etykiety?
3. Czy możliwe jest wykluczenie danego konta z otrzymywanych powiadomień?
4. Czy możliwe jest otrzymywanie powiadomień dla danej kategorii (Główne, Oferty, Społeczności, Powiadomienia lub Fora)?
5. Jak uzyskać powiadomienia Kalendarza Google?
6. Powiadomienia Gmail domyślnie śledzą 4 konta. Jak zwiększyć limit?

http://add0n.com/gmail-notifier-chrome.html

Tagi:
Gmail, e-mail, powiadomienia poczty internetowej, menedżer Gmail
```
Note that this description seems little outdated (like `Gmail notifier only monitors 4 accounts by default`). If important changes, let me know, so I will correct aboves.

Description for Chrome addons page:
```
Powiadomienia Gmail to rozszerzenie Chrome, które powiadamia o przychodzących wiadomościach ze wszystkich Twoich etykiet z kont Poczty Google.

Cechy:
1. Obsługa wielu kont.
2. Obsługa wielu etykiet.
3. Małe zużycie przepustowości łącza dzięki technologii RSS.
4. Oznacz jako przeczytane, zgłoś spam, usuń lub przenieś do archiwum z poziomu paska narzędzi Chrome.

Instalacja:
1. Aby zmienić ustawienia, przejdź do: Rozszerzenia -> Powiadomienia Gmail -> Opcje
2. Uzyskaj powiadomienia z danej etykiety: http://add0n.com/gmail-notifier-chrome.html


Kod źródłowy:
Kod źródłowy jest dostępny na Github: https://github.com/inbasic/ignotifier

Zgłaszanie błędów i śledzenie ich statusu: https://github.com/inbasic/ignotifier/issues?state=open

Dalsza pomoc:
Uzyskaj więcej instrukcji na stronie: http://add0n.com/gmail-notifier.html
```

Are Firefox addons page also supports translations?

Also note that it could be nice to translate http://add0n.com/gmail-notifier.html if possible.

**Comment by inbasic** [comment]
I added a new resource to transifex.com to have a single web store content for all browsers. I am still not sure if Firefox supports localization though.

**Comment by yfdyh000** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_extension_metadata_on_addons.mozilla.org

**Comment by inbasic** [comment]
Localizations are submitted for Firefox, Chrome, and Opera.

**Comment by odie2** [comment]
Link to opera extensions website from 
http://firefox.add0n.com/gmail-notifier.html
should be changed from

https://addons.opera.com/en/extensions/details/gmail-notifier/?display=en

to

https://addons.opera.com/extensions/details/gmail-notifier/

due language redirect.

**Comment by inbasic** [comment]
done

**Comment by odie2** [comment]
Note that 

https://addons.opera.com/extensions/details/gmail-notifier/

no

https://addons.opera.com/en/extensions/details/gmail-notifier/

because your link is English UI only. My link is autoredirect based on browser language (pl -> https://addons.opera.com/pl/extensions/details/gmail-notifier/ and en -> https://addons.opera.com/en/extensions/details/gmail-notifier/)

Also please remember to update link on addon settings page.

**Comment by odie2** [comment]
The same for firefox. Replace with:

https://addons.mozilla.org/pl/firefox/addon/gmail-notifier-restartless/

And it seems like mistaked link to Safari on http://add0n.com/gmail-notifier.html - it's pointing to

https://extensions.apple.com/

**Comment by inbasic** [comment]
Fixed. Thanks

**Comment by inbasic** [comment]
Gents, the new Gmail notifier needs locale update. Also I would appreciate if you guys can check the latest beta version to make sure it is not buggy. 

The new things to keep eye on:

1. If you mark a message as read from Panel while having an open Gmail page, the counter on page should update shortly.
2. By marking a message as read in the Gmail interface, the toolbar badge number should update itself shortly.
3. The notifier only executes notifications only and only if new emails arrive. So if you mark an old email as unread, the badge notification should update, but no sound is played anymore (considering the email has not been arrived within the past 10 minutes)

Firefox users can get the latest dev version from:
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Opera users need to download the "multi-borwser" branch, 
https://github.com/inbasic/ignotifier/tree/multi-browser

Thanks!

**Comment by inbasic** [comment]
@KissDaniGH please read my last post in this thread

**Comment by odie2** [comment]
@inbasic 
Emm, I could test latest version on Opera, but I really don't like install useless libraries and programs to just compile extension one time.
Could you compile it for me, please?

**Comment by inbasic** [comment]
@odie2 there is no need to install anything. Just download the entire "multi-borwser" branch and point Opera to `src.safariextension` folder as the extension root.

**Comment by odie2** [comment]
@inbasic Ok, got it.

But something looks like broken:
![image](https://cloud.githubusercontent.com/assets/9401878/8634110/4a552e2e-27eb-11e5-854b-f377ebefc060.png)
("Czerwony dla ..." is colors for icon state)

**Comment by inbasic** [comment]
There are two new translations,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/_locales/en/messages.json#L354-L359

Maybe if you modify the locale file, this will be fixed?

**Comment by inbasic** [comment]
got it! let me push an update

**Comment by inbasic** [comment]
Please download a new copy and replace the old one.

**Comment by odie2** [comment]
Yes, now it's good.
Polish translation updated.
For me those 3 points works fine.

Isn't new option should have default option set? For me default is empty number input.

**Comment by odie2** [comment]
Seems like forgotten debug print:
![image](https://cloud.githubusercontent.com/assets/9401878/8634182/de1f198c-27ee-11e5-823f-a0183c9cc881.png)

**Comment by inbasic** [comment]
@odie2 fixed, https://github.com/inbasic/ignotifier/commit/77289cd3d5d503110a33c765850eef12d4067215
