### ISSUE TITLE
Addon completely broken/unuseable 

### ISSUE THREAD

**Issue by Theotherguy1223** [inbasic/ignotifier#315]
last week, I left my browser (firefox) open on the youtube homepage while I went to watch tv for a little while. When I came back, my firefox had restarted, and all my plugins were gone. I re-installed them all, but now 2 of them don't work. (those being Gmail Notifier (restartless) and Stream Notifier.)

I'm signed into my gmail account, the icon for the notifier is there on my bar, but clicking it does nothing, it never changes or updates, whenever I get mail, it does nothing. When I open my options for the addon, this is what pops up, and never changes:

http://puu.sh/hig7O/780b8976de.png

The Button: 

http://puu.sh/higdb/9a3816f8bd.png

Any help is appreciated

**Comment by GedeonV** [comment]
Same thing for me firefox restart , and reset all of my addons , i load a old profile but Gmail Notifier and Live Stream Notifier doesn't work , help :'(

**Comment by Theotherguy1223** [comment]
I've since tried everything I can thing of, refreshing firefox, cleaning my regisrty, restarting my computer with a combination of uninstalling firefox, all with the same result: Nothing

**Comment by inbasic** [comment]
Follow FAQ 9 to see if it helps,
http://add0n.com/gmail-notifier.html

**Comment by Theotherguy1223** [comment]
FAQ 9 did NOT solve the issue, even with a new profile, and it being the only addon, without importing anything into the new profile, AND deleting the old profile without first starting the new profile, the addon still refuses to work. (and yes, I was signed into gmail)

**Comment by inbasic** [comment]
@Theotherguy1223 so the icon is blue?

Can you open [https://mail.google.com/mail/u/0/feed/atom](https://mail.google.com/mail/u/0/feed/atom) in your browser (normal mode, not private mode) without entering your credentials?

**Comment by Theotherguy1223** [comment]
yes, I can open that without credentials in normal mode

**Comment by inbasic** [comment]
Okay then. Close all your Firefox windows. Now open a single window and then hit Ctrl + Shift + J. Console window will be opened. Uncheck all tabs except JS and Log then take an screenshot of the errors and share it here (you can drop the image into the edit box)

**Comment by Theotherguy1223** [comment]
And done. This is in the new profile, with only gmail notifier installed

![ca8e4d3fb8](https://cloud.githubusercontent.com/assets/12008758/7220243/6e12c216-e68e-11e4-956e-71a543c0a6af.png)
![f1c2e94337](https://cloud.githubusercontent.com/assets/12008758/7220242/6e12428c-e68e-11e4-9c8c-4eec60b28456.png)

**Comment by inbasic** [comment]
Click on one of `Object { ....}`'s and take an screenshot from the right panel

**Comment by Theotherguy1223** [comment]
Hope I did that right

![09de17f8a9](https://cloud.githubusercontent.com/assets/12008758/7220445/15af632a-e695-11e4-8fce-76117949e355.png)

**Comment by inbasic** [comment]
Yes, that was exactly what I was looking for. I made a custom version for you to track the error,
Please download the XPI file and then drag & drop it into your Firefox. After installation is done, you should get a log in the console starting with "1" or "2" (hopefully just before `Object {...}` error hits). Just paste the log here.

﻿https://www.dropbox.com/s/tn1ce9d5s5v6fzo/ignotifier.xpi?dl=0

**Comment by Theotherguy1223** [comment]
Seems to be no change except for the DeadObjects, and they have no log

![8cb7e1dbb2](https://cloud.githubusercontent.com/assets/12008758/7220598/cc571c66-e69b-11e4-8bb6-d01c0ece8687.png)

**Comment by inbasic** [comment]
That's weird! for some reason, the config has no access to the main library and hence the extension cannot initiate. Normally installing the extension on a clean profile should have fixed the bug. I have no idea why it didn't help in your case.

In the console window, on right panel, there is an item labeled as  `stack`. Can you copy the text in front of it and past it here?

**Comment by Theotherguy1223** [comment]
stack:"config.tray.time.notification@resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/lib/config.js:557:14
@resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/lib/wrapper/firefox/tray/winnt/tray.js:170:1
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
tray<@resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/lib/wrapper/firefox/tray/wrapper.js:7:1
@resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/lib/wrapper/firefox/tray/wrapper.js:5:13
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
@resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/lib/wrapper/firefox/app.js:429:16
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
@resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/ignotifier/lib/common.js:7:13
CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:129:18
run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19
startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7
Handler.prototype.process@resource://gre/modules/Promise-backend.js:870:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:749:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:691:37
"

**Comment by inbasic** [comment]
How about this version,
https://www.dropbox.com/s/tn1ce9d5s5v6fzo/ignotifier.xpi?dl=0

Do you still get an error? If so please provide the screenshot of the right panel

**Comment by Theotherguy1223** [comment]
It seems like you're putting a lot of effort into this just to help me, thank you, I really appreciate it.

![9f6c94f0c5](https://cloud.githubusercontent.com/assets/12008758/7234324/51a6c5d4-e754-11e4-9412-c514052ab000.png)

**Comment by Theotherguy1223** [comment]
not sure if it helps, but the other problem I'm having with firefox atm is that after I quite firefox, the position of the bookmark bar resets until I go into the customize screen, then it fixes itself automatically, not sure if that could have anything to do with this or not.

Also, using Windows 8.1

**Comment by Theotherguy1223** [comment]
Just want to say that this is still an issue for me

**Comment by inbasic** [comment]
How about now?
https://www.dropbox.com/s/tn1ce9d5s5v6fzo/ignotifier.xpi?dl=0

If it didn't work, please provide the right panel screenshot as well as the full stack message.

**Comment by Theotherguy1223** [comment]
That version works fine on the separate profile with no addons, should I try install it to my profile with all my other addons? because the one in my main profile still doesn't work

**Comment by inbasic** [comment]
Yes, why not!

**Comment by Theotherguy1223** [comment]
it works, thank you, but could you please explain to me what the problem was? so I have a better understanding?

**Comment by inbasic** [comment]
Great!

For some reason the tray module is unable to load user configurations, and hence prevented the extension to initiate. I defined a set of hard coded configs in the tray module to be used in the case the actual configs are unavailable.

**Comment by GedeonV** [comment]
the link to dropbox it's dead can you put a another one ??? i think it's will work for me i have exactly the same error for each step

**Comment by inbasic** [comment]
Use the latest beta version,
https://addons.mozilla.org/en-US/developers/addon/gmail-notifier-restartless/versions
