### ISSUE TITLE
icon does not show counter

### ISSUE THREAD

**Issue by jakijem** [inbasic/ignotifier#317]
The windows bar icon, nor the firefox icon doesn´t show the counter, it always appear in grey...
(of course, no preview available, as it doesn´t find any new mails)
Any issue in the config?

**Comment by inbasic** [comment]
If the icon is grey, it means the extension is working fine but could not find any unread emails in the connected account(s). So how many unread emails do you have in your primary account?
https://mail.google.com/mail/u/0/?tab=wm#inbox

**Comment by jakijem** [comment]
I hacve several unread mails, but the extension doesn´t find them as unread so it doesn´t show any counter

**Comment by inbasic** [comment]
Are the unreads from your primary account (https://mail.google.com/mail/u/0/)? 

If not make sure you have label `inbox` in the Feeds section of options page.

**Comment by jakijem** [comment]
I think so, 
in the feeds sections I have this: https://mail.google.com/mail/u/0/#inbox

**Comment by inbasic** [comment]
Nope, insert `inbox` in `Primary account (/mail/u/0/)` til `Senary account (/mail/u/5/)`

**Comment by jakijem** [comment]
I dont understand, is it right?

![settings](https://cloud.githubusercontent.com/assets/12017486/7220388/412d73fe-e6c5-11e4-9b99-23147944c157.jpg)

**Comment by inbasic** [comment]
Like this,
![screen shot 2015-04-19 at 21 37 40](https://cloud.githubusercontent.com/assets/351062/7220529/0046ebb6-e6e0-11e4-9e94-adca096ed113.png)

**Comment by jakijem** [comment]
That´s it! Its working perfect,  thank you!

**Comment by inbasic** [comment]
Great!
