### ISSUE TITLE
Feature Requests: Keyboard shortcuts & Unread messages first

### ISSUE THREAD

**Issue by dan-earle** [inbasic/ignotifier#319]
Would it be possible to have some keyboard shortcuts, e.g, <Ctrl>R to mark the top message as read, then you can quickly skip over junk that you might read on a slow day but today you just want to clear your unread messages fast.

To go along with this you would need an option to show unread messages first which you can do in Gmail

**Comment by inbasic** [comment]
In the settings page there is an item, `Support keyboard shortcuts on the toolbar panel`. Have you enabled it?
