### ISSUE TITLE
Feature request:  Mute notifications in right click menu

### ISSUE THREAD

**Issue by jprice88** [inbasic/ignotifier#320]
As someone who regularly has to share my screen/browser (projectors, webex, etc), it would be great to have quick access to enable/disable the desktop notifications via the right-click menu of the gnotifier icon. 

Thanks!

**Comment by Nekomajin42** [comment]
Good idea!

**Comment by inbasic** [comment]
This feature is available on Firefox version for a long time. The next Chrome version will have three new options:

+ Disable notifications for 5 mins
+ Disable notifications for 1 hour
+ Enable notifications

The Firefox version has a more comprehensive range support, but in Chrome we cannot have more than 5 items in the right click menu
