### ISSUE TITLE
Notifications stopped

### ISSUE THREAD

**Issue by psychmeds06** [inbasic/ignotifier#321]
The notifier is completely broken. They don't come up at all anymore and I know I'm getting email because my phone is getting notifications. The add-on used to be my phone to emails but nothing comes up at all.
I'm uninstalled it and reinstalled it. I've enabled notifications and looked at the settings multiple times. Still nothing.

**Comment by inbasic** [comment]
Please follow FAQ 9,
http://add0n.com/gmail-notifier.html
