### ISSUE TITLE
No toolbar icon to be found anywhere

### ISSUE THREAD

**Issue by Cairenn** [inbasic/ignotifier#323]
It shows up fine on my other computer, but while setting it up on this system the icon is nowhere to be found.
*  both systems running Windows
*  both using the latest Firefox
*  both using all the same firefox addons
*  both signed in to the same three email accounts
*  both with all the same options checked on the integrated gmail notifier options page
used the same version of ig notifier
*  tried uninstalling then reinstalling, with restarts even though it shouldn't be necessary
*  taskbar icon shows up fine, but will only show for the primary email address
*  tried using the latest beta version, again with restarts

Still no joy.  Any suggestions?

**Comment by inbasic** [comment]
Have you read FAQ9, http://add0n.com/gmail-notifier.html?

**Comment by RVoiseyFirstApp** [comment]
This has just happened to me, exact same issue except I'm using a mac. There is no toolbar icon or anything in customize. I also am not getting any desktop notifications.

**Comment by inbasic** [comment]
Can you confirm the problem on a clean profile? Have you followed FAQ 9?

**Comment by Cairenn** [comment]
The problem is that there is no icon anywhere to be found.  Period.  Not that it won't show only one inbox, not that it won't show a specific category.  It just flat out isn't there, at all.  FAQ9 can't help us if we can't get the icon in the first place.  See my original post.

**Comment by inbasic** [comment]
Well I meant FAQ 10

**Comment by inbasic** [comment]
Also try the latest dev version,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download the XPI file and drop it into your Firefox

**Comment by RVoiseyFirstApp** [comment]
@inbasic 
Can confirm on a clean profile it does NOT solve the problem following FAQ 10, i.e. the icon still does not appear.
However with the dev version it has re-appeared; thanks very much!

**Comment by beherit** [comment]
The problem with disappearing icon is irritating! I tested many extensions and only THIS have such problem. Every time I turn the Firefox I must re-add icon to toolbar.

**Comment by inbasic** [comment]
@beherit usually if you install the extension on a clean profile the problem resolves.
Read FAQ 10, http://add0n.com/gmail-notifier.html

**Comment by beherit** [comment]
Yes, You right but problem appear again after few days (when we install others extensions and just use Firefox). Sorry but I don't want to clean my profile 2-3 times in week. This is big problem, cleaning profile is only temporary solution.

**Comment by Cairenn** [comment]
Using the dev version was the thing that finally fixed it for me.  inbasic linked it above.  :)

**Comment by inbasic** [comment]
If the problem is back after a few days, most probably GN is conflicting with another extension of yours. The notifier uses the standard way to add the toolbar button (assuming you are on the latest release of Firefox). So without further debugging I cannot be sure what extension is causing the conflict and why.

**Comment by beherit** [comment]
@Cairenn Dev version is 0.5.6, version from addon site is 0.5.7.2  - so I must use oldest version? O.o
@inbasic how can I turn on debugg? As I say - only THIS extension have problem with toolbar.

**Comment by inbasic** [comment]
Open all Firefox windows. Now open a single one and hit Ctrl + Shift + J. Is there anything in the console related to GN. If you are not sure take an screenshot and share it here

**Comment by beherit** [comment]
@inbasic You don't understand me. After turning on Firefox I need to re-add icon to toolbar. Then I turning off Firefox and turning on and again icon disappear and I must re-add it.

**Comment by beherit** [comment]
In the console there is no error related to GN.

**Comment by beherit** [comment]
Here is errors from console:

![2015-09-24_201359](https://cloud.githubusercontent.com/assets/5073817/10082268/233c3780-62f9-11e5-8d98-8c2f4d90a271.png)

As I test - icon disappear when I restart Firefox (e.g. when I install some addon that need restart).

**Comment by beherit** [comment]
Any idea how to solve this problem?

**Comment by beherit** [comment]
@inbasic please help :)

**Comment by inbasic** [comment]
@beherit you have an extension that conflicts with GN. Can you temporary disable the extension(s) responsible for the errors in the console (like the one cause `overlay.js:397` error) and see if it helps?

**Comment by beherit** [comment]
No, this problem exists on clean profile too.

**Comment by inbasic** [comment]
What is your Firefox version?

**Comment by beherit** [comment]
The latest stable version ;)

**Comment by inbasic** [comment]
I have no idea if it occurs on a clean profile too.  Try to start your Firefox with `-jsconsole` and see if you can catch more initial errors,
https://developer.mozilla.org/fr/docs/Mozilla/Command_Line_Options#-jsconsole

**Comment by beherit** [comment]
As I previously wrote - icon disappearing from toolbar after restart Firefox (I mean killing/restart process or restart Firefox when we install some addon what need restart)

**Comment by inbasic** [comment]
Firefox goes through the same process after a restart or startup. So when you close all your Firefox windows and open a new window, the icon appears but when you install a new non-restartless extension and Firefox restarts itself the icon disappears?

**Comment by beherit** [comment]
Icon disappears ONLY when I restart Firefox (e.g. when I install non-restartless extension). When I normally run Firefox the icon is still in toolbar.

**Comment by inbasic** [comment]
That's weird! Okay then try to start Firefox with the `-jsconsole` command from command line. Then restart Firefox by installing a non-restartless extension. As far as I remember the console will remain active and you can still see messages in the console window (By console I mean command prompt, CMD)

**Comment by beherit** [comment]
Parameter `-jsconsole` is not remember after restart and console is not to remain active. Many problem with this icon - others Firefox addons don't have such problems! It's frustrating.
