### ISSUE TITLE
[Feature Request] Option to Star and mark as Important

### ISSUE THREAD

**Issue by seba-g** [inbasic/ignotifier#325]
Would be very usefull!

**Comment by klint** [comment]
I was about to ask the same thing when I saw this post :)
The absence of these features is the main reason for me to still open the Gmail page actually.
Thanks

**Comment by ildarkhasanshin** [comment]
+1

**Comment by KeronCyst** [comment]
I would love to be able to star messages from the preview pane, too.

**Comment by inbasic** [comment]
Star is already implemented. We might have the important tag in the future releases as well when the star plug-in is stable.
