### ISSUE TITLE
Disable nag to login

### ISSUE THREAD

**Issue by Xinok** [inbasic/ignotifier#326]
When you aren't logged into any Gmail accounts, this add-on will start nagging you to login and will even open multiple tabs with the Gmail login page. Despite being very annoying, it may occur when there are network issues and it's unable to connect to Gmail. Also, I have a copy of Portable Firefox on my flash drive which runs in private browsing mode, so of course I'm not logged in when this browser starts.

Could you provide an option to disable this please?

**Comment by inbasic** [comment]
Well, with the factory settings, the icon turns blue when you are not logged-in, that's it!
Try the notifier on a clean profile, https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
