### ISSUE TITLE
No sound on firefox 39

### ISSUE THREAD

**Issue by fireattack** [inbasic/ignotifier#327]
Win 7 x64, firefox 39 beta.

The notification sound for new mail just stops working. I never changed any settings, but it's broken days ago (can't remember the exact date, sorry).

I tried to install it to a brand new profile of Firefox with all default settings, still same problem.

**Comment by inbasic** [comment]
On a clean profile, open the Error console (Ctrl + Shift +J). Now middle click on the toolbar button to force recheck your emails. Considering you have an unread email in your inbox, the sound notification should be played, or an error will appear in the console. Take an screenshot of the error and drag & drop it here.

**Comment by fireattack** [comment]
![a](https://cloud.githubusercontent.com/assets/4130991/8309137/4b028c34-19fb-11e5-8cd0-34b12d7f6fc9.png)

**Comment by inbasic** [comment]
The problem should have been fixed now in the latest beta version,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download this XPI file and drag & drop it into your Firefox browser.
