### ISSUE TITLE
Stop working on Iceweal

### ISSUE THREAD

**Issue by dbourrion** [inbasic/ignotifier#328]
Hi
I was using that amazing plugin on iceweal (the dedian firefox, to say it quickly) and it was working perfectly.

For some says now, the gmail notifier icon has disappear. I've try to reinstall it, everything looks ok during the installation but no icon anymore.
When I'm opening the preferences of the gmail notifier, I got a small windows with nothing inside.

Any idea to help me ?
Thanks
D.

**Comment by inbasic** [comment]
Close all your browser windows. Open a single window and then open Error console (Ctrl + Shift + J). If there is an error there take an screenshot and drop it here.

**Comment by dbourrion** [comment]
![gmailnotifier](https://cloud.githubusercontent.com/assets/400398/8540382/85698190-2485-11e5-9c80-4d705d2885ce.png)

**Comment by inbasic** [comment]
See these `Object {}` Click on one of them. A right side panel opens up. I need an screenshot from that

**Comment by dbourrion** [comment]
![gmailnotifier1](https://cloud.githubusercontent.com/assets/400398/8540539/f58ed8de-2486-11e5-9633-86bd0105c2b3.png)

**Comment by inbasic** [comment]
Is this fixed,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download the XPI file and drag & drop it into your Firefox

**Comment by dbourrion** [comment]
The xpi file you gave me fixe it
Many thanks
D
