### ISSUE TITLE
When using full preview mode in Chrome, action buttons disappear.

### ISSUE THREAD

**Issue by ReanimationXP** [inbasic/ignotifier#330]
![screen shot 2015-07-07 at 10 24 04 am copy](https://cloud.githubusercontent.com/assets/2142085/8552646/395355fc-2493-11e5-883a-b8806bc7b094.png)

^ Pretty much says it all :) 

Chrome  43.0.2357.130 (64-bit) on OSX Yosemite (think I noticed it on Windows 7 too)
Gmail Notifier  0.5.5

**Comment by inbasic** [comment]
Is this happening for all emails? or just a few?

**Comment by ReanimationXP** [comment]
All.

-Drew

**Comment by inbasic** [comment]
What are the values you use for width and height in the settings?

**Comment by ReanimationXP** [comment]
750,
900.

I really hope that "toolbar" height and width isn't actually affecting that
toolbar's position. My understanding was it affected the preview popup
window size.. if it doesn't that is a senseless setting lol

-Drew

**Comment by ReanimationXP** [comment]
would explain why it wasn't working when trying to set the window size..

-Drew

**Comment by inbasic** [comment]
Well, it turned out that there are maximum width and height limit for Chrome popup window. The next version will check the entered values and correct them, meanwhile make sure the width is not more than 780px and height limit is 600px.

**Comment by ReanimationXP** [comment]
Ah, roger.

-Drew

**Comment by ReanimationXP** [comment]
Cool that worked, thanks :)

-Drew

**Comment by inbasic** [comment]
Perfect. Thanks for the report.
