### ISSUE TITLE
Does not save any changes

### ISSUE THREAD

**Issue by Tracas** [inbasic/ignotifier#332]
Hello, in the configuration of pluguin not save me any changes since the last version, for example, if I distanced box Display desktop notification for new emails and then, close firefox, opening again firefox and then gmail notifier again, and it is still displayed in the taskbar notification .
If you need more info, tell me :) and sorry for my bad english.
Greets!

**Comment by inbasic** [comment]
Can you confirm the fix on the latest dev version,
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download the XPI and drop it into your Firefox browser

**Comment by Tracas** [comment]
Hello again, dowload the xpi file and drop in a new tab. Close firefox and then open gmail notification through the button. Open settings, uncheck the option Display desktop notification for new emails and nothing :/. I'm using the last version of firefox 39.0, but i don't know if that info could be useful for this.
Thanks for your time :)

**Comment by inbasic** [comment]
So it still does not save your preferences? If so please try the extension on a new profile,
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Tracas** [comment]
Hello, I've created a new profile and installed the extension you told me (It's the only one I've installed in that new profile), but it's still not working. I've compaired my notifier options with a friend's (his notifier works perfectly), and there's a little difference between them (although we have the same version)... may be that the reason why it`s not opening in a new tab instead of a pop up panel?
http://i59.tinypic.com/wv8wid.jpg
http://i59.tinypic.com/2nvbaj4.jpg
Thanks for your time!

**Comment by inbasic** [comment]
I guess the difference is the second screenshot is taken from the dev version, the other one is the Mozilla's webstore version.

So in the dev version, the only problem you are facing is that the taskbar notification is still showing up? Can you change the other settings?

**Comment by Tracas** [comment]
No, the only option i can change is "play alert sound for new emails" the others options dont save any change.

**Comment by inbasic** [comment]
I am releasing a new version today. Please reopen if the problem is not fixed
