### ISSUE TITLE
Updated icons

### ISSUE THREAD

**Issue by gaberad** [inbasic/ignotifier#333]
Here's a rar file with updated icons to match the current gmail icon style, if you wanted to use them.

https://mega.co.nz/#!iBVDhb5K!lPbT-mdIy0jKE-cd5hnE_sS_021XiRRAE0cpgF1ySbQ

**Comment by inbasic** [comment]
Hi,

there is no plan to use a new set, however, you can make a userstyle to change the current icon set, and this might be useful for others as well.

**Comment by gaberad** [comment]
Yeah, I tried creating a userstyle, but couldn't get it to replace the toolbar icons. Do you happen to know the css to do it?

**Comment by inbasic** [comment]
Well, it doesn't seem to be an easy way to replace the default set.
