### ISSUE TITLE
Gmail notifier, exclude multiple accounts etc?

### ISSUE THREAD

**Issue by DajsDK** [inbasic/ignotifier#334]
I've been trying out gmail notifier.

I want to exclude multiple accounts and only want the notifier to check my primary account - but no matter what I do, it will check all my accounts. What to do?

Also I want this way of notification instead of the upper right corner og the chrome browser: http://screencast.com/t/gCpBygEjgA
How to do that?

**Comment by inbasic** [comment]
add label `inbox` to the `Primary account (/mail/u/0/)` in the settings, and leave the rest boxes empty.

> Also I want this way of notification instead of the upper right corner og the chrome browser: 

The tray notification is only available in Firefox version. Chrome API does not allow access to system level APIs

**Comment by DajsDK** [comment]
Ok, thx.

How to enable the tray notification in Firefix version?

**Comment by inbasic** [comment]
In windows, it is active by default.

**Comment by DajsDK** [comment]
Come on please... by all respect; that answer wasnt that helpful. 

No hard feelings but...  "in windows"? Also, I'm running FF right now - I've installed the app, but it only shows top right and not in tray... så apparently I need to do something specific to enable it...

**Comment by inbasic** [comment]
what is your OS? 
Note that the tray is only shown when there is an unread email in the inbox folder

**Comment by DajsDK** [comment]
Win7 Home premium.

**Comment by inbasic** [comment]
so even when there is an unread email in your inbox, meaning, the badge number is appearing over the toolbar button, still there is no icon in the tray? Also check hidden icons as well, http://windows.microsoft.com/en-us/windows7/change-how-icons-appear-in-the-notification-area
