### ISSUE TITLE
UNABLE TO ADD EXTENSIONS 

### ISSUE THREAD

**Issue by chaterjeehindal** [inbasic/ignotifier#337]
Dear All,
I have a CHROME is my PC. But i am unable to add extensions. 
![chrom](https://cloud.githubusercontent.com/assets/13416138/8774268/f002201a-2ef9-11e5-8f10-c73dd05fa795.JPG)

**Comment by inbasic** [comment]
That's probably has noting to do with the extension. Your internet connection might be unstable. Can you get another extension from the store?

**Comment by chaterjeehindal** [comment]
no, not happening. not a single extension. also unable to update

**Comment by chaterjeehindal** [comment]
HELLO !!! I AM WAITING FOR YOUR REPLY

**Comment by inbasic** [comment]
I dont think I can help! You need to fix your network connection
