### ISSUE TITLE
Gmail notifier doesn't notifiy me...

### ISSUE THREAD

**Issue by etblo** [inbasic/ignotifier#339]
hi, i need help with this, i have two seprate emails, and i put them in the labels, and i am not getting notified at all. i don't know if i typed it wrong.. i put E******c@Gmail.com   (i don't want to include my real email in this thread) and then i put my other email E*****t@gmail.com. did i do something wrong or does the notification's just not work?

**Comment by inbasic** [comment]
There is no need to insert your email address at all. Just insert label `inbox` in the "Gmail" section of options page under "Primary account (/mail/u/0/)" and "Secondary account (/mail/u/1/)" fields
