### ISSUE TITLE
Does not change sound

### ISSUE THREAD

**Issue by icebergy** [inbasic/ignotifier#341]
Hello, 
I want the notification to not play any sound. I have unchecked the "Play alert sound for new emails" box, put the sound to the minimum (1, because if I put 0, it changes it to 80 (?!)) and even chosen "user defined sound" without chosing any sound, in the hope that it just won't make any sound... (it was my last hope...) but it still does the default sound every time I get an email. How can I fix that?

**Comment by inbasic** [comment]
You just need to uncheck "Play alert sound for new emails" that's it!
Please confirm the problem on a clean profile, https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
