### ISSUE TITLE
Clicking desktop notification does not go to email

### ISSUE THREAD

**Issue by mdmower** [inbasic/ignotifier#342]
Windows 8.1 Pro 64bit
Chrome Version 44.0.2403.107 m (64-bit)
Gmail™ Notifier 0.5.5

When a desktop notification appears, clicking the notification dismisses it. I would expect clicking the notification to take me to the email before dismissing.

**Comment by mdmower** [comment]
Same result with:
Ubuntu 15.04 64bit
Chrome Version 44.0.2403.125 (64-bit)
Gmail™ Notifier 0.5.5

**Comment by inbasic** [comment]
This is a Chrome specific problem. In Firefox version popup is opened when desktop notification is clicked, but Chrome does not allow this, so from the next version message will be shown in a new tab.

Thanks for the report.
