### ISSUE TITLE
GMail no longer opens in new tab when I click the taskbar icon.

### ISSUE THREAD

**Issue by GoblinGuide** [inbasic/ignotifier#344]
After updating to the newest version (0.5.6) with Firefox 39.0, I can't get the taskbar icon to open up a new tab. It just gives me the popout window. This is true regardless of my settings under "Tab Opening" - literally whether they are all checked, all unchecked, or any other illogical combination thereof, in addition to the one I actually want, which is "Open new Gmail account next to the active tab".

What am I doing wrong?

**Comment by cianoz** [comment]
I was looking for a Gmail notification addon and found this, but I immediately uninstalled for the same reason. I'd like to have the option to open Gmail webpage just with a click.

**Comment by inbasic** [comment]
Is this fixed on the latest release?

**Comment by StaplerGuy** [comment]
Not for me, no.

**Comment by StaplerGuy** [comment]
Still unfixed for me personally. Can't speak for anyone else.
