### ISSUE TITLE
"Read and change all your data on the websites you visit"

### ISSUE THREAD

**Issue by Rayna-Grimm** [inbasic/ignotifier#347]
"Read and change all your data on the websites you visit"
what does this mean? what are you guys going to be doing if i allow your gmail notifier to stay installed. i had a plugin that got malware and one day some text on every web page that i visited and hovered over ended up showing ads. 
the new permission details reminds me of that and i would like some more detail on exactly what this means

**Comment by inbasic** [comment]
The new permission is related to this commit,
https://github.com/inbasic/ignotifier/commit/c8567319e253a71772df13819046942cfb356955

Basically the notifier now can listen for all sort of email read and write requests and can update the badge number accordingly. Previously if you made a change from for instance Gmail interface, the notifier was not aware until the new update; but, now the notifier monitors network activities and trigger an update as soon as such a behavior is observed.

It might be possible to lower down the permission to Gmail only, but then if a user uses another Gmail extension or uses a different Gmail UI, most likely read/write requests will be missed. Still I am going to take a look at the maximum required permission one more time.

**Comment by inbasic** [comment]
@Rayna-Grimm I pushed a new version and the permission is back to "http(s)://mail.google.com/*". I'll still keep this open in case the permission change causes any problem

**Comment by Rayna-Grimm** [comment]
thank you for the information and i have an update on things

while checking may main email (/mail/u/0/) today a second after clicking on the "promotions" tab the page goes back to the main "primary" tab making it difficult to check things in the other tab. also did it once with "social tab"

 after moving some thing the to promotions folder in my (/mail/u/1/) account, it began doing the same thing and the problem only stopped after disabling the notifier extension and after re-enabling it the problem began again 

looks like its trying to keep me away from ads instead of my previous worries. though i would like to see these since i signed up for them xD

**Comment by inbasic** [comment]
This certainly is a bug. I pushed a new version to Chrome store fixing this. You can try version 0.5.7.2 and see if the problem is fixed or not.

**Comment by Rayna-Grimm** [comment]
it looks like everything is working fine again. sorry about the very late reply and thank you
