### ISSUE TITLE
Nbr of emails changed from exact number to "grater than" from 0.5.7+

### ISSUE THREAD

**Issue by j00zef** [inbasic/ignotifier#349]
Hi
There is a change in displaying the actual number of unreaded messages in toolbar icon which is especially visible when having big amount of unreaded mails (probably more than 1k).
Previously even though I had 3k+ mails, the counter displayed exact number of messages, now in the latest version there is indication than I have >2k unreaded.
Why this is important? It is easy to keep an eye on counter to see if there is new email without email notif or sound played - I used to set undread emails number to certain level ( for instance 3200) so anything above 3200 indicates that new email has arrived. Now I need to switch back email notif which works for me only when I am next to my pc.
Please bring back exact number of unreaded emails (maybe an option or dev flag).

**Comment by inbasic** [comment]
In the latest dev version, there is a new option in the "Miscellaneous" section to let you configure this.
https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

Download the XPI and drop it into your Firefox browser.

**Comment by j00zef** [comment]
Excellent, already updated and it works as intended thanks!
