### ISSUE TITLE
[Question] What does "Only fire desktop and sound notifications when email has arrived in less than" mean, and how can I disable it?

### ISSUE THREAD

**Issue by mleyen** [inbasic/ignotifier#355]
Does that mean it does not notify me on emails older than 10 minutes?

Most emails I actually recieve are listed as older, as I set Gmail to retrieve messages from an external POP3 server, so it shows the original message time instead of the download time.

Also, is there a way to disable this feature entirely and have the addon notify me regardless of message time? Would setting the value to 999999 or similar work?

**Comment by inbasic** [comment]
> Would setting the value to 999999 or similar work?

Yes! but not recommended! In this case if you deliberately mark an old message as unread the notifier will notify you.
