### ISSUE TITLE
Mouseover Not Working

### ISSUE THREAD

**Issue by bob603** [inbasic/ignotifier#357]
I got notification of update this morning. Since then, when I mouseover the notification icon, it does not show which accounts have mail. Only the main notification (with number of items overall) works. I checked the settings, don't see anything that would affect this. Any ideas?

**Comment by inbasic** [comment]
Thanks for the report. It is now fixed on the latest dev built,

Download the XPI and drop it into your Firefox browser

https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true

**Comment by bob603** [comment]
thanks guys

On Tue, Oct 13, 2015 at 4:17 AM, InBasic <notifications@github.com> wrote:

> Thanks for the report. It is now fixed on the latest dev built,
>
> Download the XPI and drop it into your Firefox browser
>
>
> https://github.com/inbasic/ignotifier/blob/multi-browser/src.safariextension/executables/ignotifier.xpi?raw=true
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inbasic/ignotifier/issues/357#issuecomment-147642794>.
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~
