### ISSUE TITLE
Preview of email not popping up, only opening/switching to gmail tab

### ISSUE THREAD

**Issue by aelberling** [inbasic/ignotifier#361]
sometimes when i mouse hover over the icon, it doesn't tell me which accounts have unread messages. when this happens, it will no longer display the preview for unread messages on click, but rather switches to an open gmail tab or opens a gmail tab.

**Comment by inbasic** [comment]
So if for any reason GN cannot access to the Gmail server, the icon turns to blue. during this period popup is not accessible as well.
