### ISSUE TITLE
net::ERR_IO_PENDING in Chromium 

### ISSUE THREAD

**Issue by nitrobg** [inbasic/ignotifier#362]
GET https://mail.google.com/mail/u/0/feed/atom?rand=5791669 net::ERR_IO_PENDING
app.get @ app.js:115
execute @ server.js:144
(anonymous function) @ common.js:275
checkEmails.execute @ common.js:274
(anonymous function) @ timer.js:39

This error message happens every X seconds, depending on the check interval. The icon often turns blue and doesn't report the new messages.
The browser is Chromium 48.0.2558.0 (Windows 64-bit) but the same happens on older versions as well.

**Comment by inbasic** [comment]
This doesn't seem like GN bug. I assume you have an unstable internet connection, right?

**Comment by nitrobg** [comment]
It was most likely a browser-related issue because it disappeared after an update to v50.
