### ISSUE TITLE
Can't interact with emails from preview window (Inbox?)

### ISSUE THREAD

**Issue by tdtm** [inbasic/ignotifier#366]
Browser: Chrome 46.0.2490.80 on OSX
Extension version:  0.5.8

I have two accounts synced with the extension. Id=0 has GMail as default, Id=1 has Inbox as default.

With Id=0, It works properly.

With Id=1, I get notifications as usual. I can open settings, GMail window from the preview popup.
I however can't do any of the GMail interaction options (Archive, Spam, Delete, Mark as read). Clicking on the button does nothing (sometimes loading, but no actual action on the emails is done).

**Comment by inbasic** [comment]
I am not able to reproduce this. Have you tried logging-out from both accounts once?
