### ISSUE TITLE
Constant crash after receiving mail.

### ISSUE THREAD

**Issue by Elektro666** [inbasic/ignotifier#367]
When new mail arrive I get sound notification and then opera crash and reopen, then again sound, crash, reopen etc... I need to read that mail on my cell phone, and then if no unread mail exists, I can run everything without a problem. When next mail arrive same thing happening, so this is not one time error.

**Comment by inbasic** [comment]
Are you using a custom sound file? With the current release I cannot reproduce this bug.

**Comment by Elektro666** [comment]
Nope, I am not even sure it is related to sound, because when I turn off sound notification same thing happened. 
I am using Opera 33.0.1990.115 and last gmail notifier I found on opera add-ons store.

**Comment by inbasic** [comment]
Okay then, please turn off all the notifications and see if the crash occurs again:

1. Display desktop notification for new emails
2. Play alert sound for new emails
3.  Display "Windows taskbar notification" or "Mac OS Dock notification" (if you also have this one)

**Comment by Elektro666** [comment]
Interesting, it looks like this fixed problem. I will test more later, and will inform you about results.

**Comment by Elektro666** [comment]
Ok, now everything work. Thank you very much. :) I even turn on sound notification and still work, so it is not problem with sound. Again, thanks. :+1:

**Comment by inbasic** [comment]
so "Display desktop notification for new emails" was causing this?

**Comment by Elektro666** [comment]
Yes, when I turn that option back on opera crash again... Maybe problem is with my win 10...
