### ISSUE TITLE
Unread mail number is drawn wrong in different themes.

### ISSUE THREAD

**Issue by RikisX** [inbasic/ignotifier#368]
When I'm using Simple White theme (https://addons.mozilla.org/en-us/firefox/addon/simplewhite/) unread mail number is showing garbled. Duplicate Tabs Closer shows badge numbers just fine.
FF 42.0 (Older version worked fine).
![clipboard01](https://cloud.githubusercontent.com/assets/5813374/11467631/0731d1b6-9752-11e5-909d-eb005318b5b1.jpg)

**Comment by inbasic** [comment]
From FF version 29.0 GN uses the built-in badge API, so there is nothing I  can do to fix this. Please contact the theme developer.
