### ISSUE TITLE
64bit Firefox seems not localized but still english

### ISSUE THREAD

**Issue by KissDaniGH** [inbasic/ignotifier#370]
hi,
64bit Firefox seems not localized but still english
regards,
Daniel

**Comment by inbasic** [comment]
So is this something new? Can you confirm on the latest dev version
https://github.com/inbasic/ignotifier/blob/master/builds/packed/firefox.xpi?raw=true

**Comment by KissDaniGH** [comment]
new is I bougth a new laptop ;)
same behavior on linux and windows. under 64 bit firefox notifier is english

**Comment by inbasic** [comment]
Can you try forcing the locale?
https://addons.mozilla.org/en-us/firefox/addon/quick-locale-switcher/?src=search

**Comment by KissDaniGH** [comment]
tried several ways. Simple quick change, change and reboot, .... no luck here.
firefox is hungarian but noti is english
On my windows 32 bit is perfect but 64 is not (same PC, same OS)

**Comment by inbasic** [comment]
I see. So maybe this is an SDK bug. Basically the GN just provides the locales, and SDK is responsible for the localization. Can you confirm this on another restart-less extension too?

**Comment by KissDaniGH** [comment]
Can u sugget one?

**Comment by inbasic** [comment]
https://addons.mozilla.org/en-US/firefox/addon/evernote-web-clipper/?src=search seems like to be a localized SDK addon

**Comment by KissDaniGH** [comment]
evernote is ok, it is hungarian.

**Comment by inbasic** [comment]
Seems like the `converter.js` wasn't compiling the `hu.properties`. Can you confirm the fix on https://github.com/inbasic/ignotifier/blob/master/builds/packed/firefox.xpi?raw=true

**Comment by KissDaniGH** [comment]
no luck here ;( still english

**Comment by KissDaniGH** [comment]
restarting firefox neede. thanks the new fix.
