### ISSUE TITLE
[Feature request] "Open THIS e-mail in GMail" button

### ISSUE THREAD

**Issue by zeird** [inbasic/ignotifier#372]
In ATOM feed links have `message_id` parameter. And if I open URL `https://mail.google.com/mail/u/0/#inbox/%message_id_here%` in a new tab, GMail opens that e-mail (or conversation, idk) automatically. This works at least in FF.

Therefore, it should be possible to implement "Open this email in gmail" button. Use case: opening an email for replying in just 1 click, instead of just opening gmail, then aiming with mouse cursor to unread conversation and clicking for the second time.

So, what do you think?

**Comment by inbasic** [comment]
Just click on the title of a message in the panel and the message opens up in a new browser tab.

**Comment by zeird** [comment]
Wow. Indeed. Thanks.
