### ISSUE TITLE
Disable notifications for custom time periods

### ISSUE THREAD

**Issue by Nekomajin42** [inbasic/ignotifier#373]
Hi!

If I remember correctly, you wrote once that there is a limit of context menu items by the API, so you decided to implement only two choices: 5 minutes and 1 hour.

How about some customisation? Two options in the settings: disable for "short time" and "long time", so we could define our own time periods.

Also, please use ItemType "checkbox" or the "enabled" property to show which menu item is in use.

Thanks!

**Comment by Muthaliza** [comment]
I agree with user Nekomajin42 - you should be able to set Disable notifications for a period of your choosing. It's incredible that the developer hadn't thought of that. Who wants notifications around the clock? I keep my PC on for days on end  with the sound on out of necessity, but I sleep in the same room. I'll consider donating as soon as the developer fixes this flaw.

**Comment by inbasic** [comment]
Thanks for the suggestion. Version 0.6.1 will have a new item in the context menu for user defined custom time.

**Comment by Nekomajin42** [comment]
Thanks!

**Comment by Muthaliza** [comment]
Great to have a developer actually listen to users, it gives one...hope!

**Comment by Nekomajin42** [comment]
Thank you for this update. However, I'd like to ask another one related to it. Can you make it possible to remove context menu items? It is becoming a little crowded.

Also, can you add icons to the items and change the "enable notifications" item to type checkbox?
