### ISSUE TITLE
Can't access contacts anymore, or open link in new tab

### ISSUE THREAD

**Issue by afalise** [inbasic/ignotifier#375]
When I try to open my Contacts, a new tab pops up but stays blank. Also, if I try to click on a link contained in an email, a new window pops open as it should, but nothing appears in it. In order to open a link, I have to right click on it and choose "Open in New Tab". Then a new tab opens and I can view the content on that page.

**Comment by inbasic** [comment]
Dont see how this is related to the extension. Anyhow, seems like your browser need a fresh install.
