### ISSUE TITLE
Firefox disable Gmail Notifier

### ISSUE THREAD

**Issue by erbi65** [inbasic/ignotifier#376]
Today my Firefox disable Gmail Notifier, because it's not verified and signed. What can I do now?
(https://developer.mozilla.org/en-US/Add-ons/Distribution)

**Comment by inbasic** [comment]
Just try reinstalling the extension from Mozilla's website. Most likely you have a beta version which is not signed.

**Comment by erbi65** [comment]
Thank you very much. Working!
