### ISSUE TITLE
Cannot open email and appears empty

### ISSUE THREAD

**Issue by JohnnyGaloshes** [inbasic/ignotifier#378]
I have been having this bug for a few days now. Tried uninstall and reinstall to no avail.

![untitled](https://cloud.githubusercontent.com/assets/10763046/12072324/b8b625b0-b0af-11e5-8bc9-893ef1e66f3e.png)

It shows i have an email but will not allow me to do anything to it like open when i click on the Gmail button, mark as read and the such. Also it will not open the appropriate e-mail anymore.

**Comment by inbasic** [comment]
Can you confirm the problem on a clean profile
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by epson950** [comment]
same problem. appears right after an update with 0.5.8 to 0.6.0

**Comment by JohnnyGaloshes** [comment]
Yes still doing it on a new clean profile

**Comment by inbasic** [comment]
Please open the Firefox error console (Ctrl + Shift + J) and clear it. Now disable and then re-enable the notifier from addons page and see if you get a new error in the console.

**Comment by epson950** [comment]
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/chrome.manifest'.
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
Warning: attempting to write 8855 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
POST 
XHR 
http://188.124.32.217:9091/transmission/rpc [HTTP/1.1 200 OK 12мс]
Warning: attempting to write 8854 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
TypeError: messageManager is undefined context-menu.js:689:2
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:9:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:30:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:36:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:56:13
Неизвестное свойство «user-select».  Потерянное объявление. index.css:90:13
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:103:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:122:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:142:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:233:13
DOMException [SyntaxError: "An invalid or illegal string was specified"
code: 12
nsresult: 0x8053000c
location: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/data/popup/index.js:5] core.js:91
TypeError: can't access dead object tab-firefox.js:98:0

**Comment by presnell72** [comment]
I'm having the exact same problem. Firefox 38.0 for Linux Mint. Gmail Notifier 0.6.0.

**Comment by inbasic** [comment]
Can you try this version
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

Download the XPI and then drop it into your Firefox browser. If you got an error preventing an unsigned XPI installation, temporary disable `xpinstall.signatures.required` from about:config

**Comment by presnell72** [comment]
inbasic, I tried your fix. At first, I disabled notifier, and installed your xpi, which firefox confirmed as being successfully installed. I'm not sure what to expect, but it didn't show up as a separate extension nor did any icons show up the toolbar. I then re-enabled notifier, installed the xpi again, but it did not seem to fix the problem - still showing the blank email preview as the screenshot above shows, and the preview buttons like "G" to go to gmail were not working. Thank you for looking into this matter.

**Comment by inbasic** [comment]
> At first, I disabled notifier,

Instead of disabling the extension, uninstall it. Then install the XPI file.

If the problem is not fixed, then follow:

> Please open the Firefox error console (Ctrl + Shift + J) and clear it. Now disable and then re-enable the notifier from addons page and see if you get a new error in the console.

**Comment by epson950** [comment]
inbasic, the problem is not fixed!
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/chrome.manifest'.
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
Warning: attempting to write 8855 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
Warning: attempting to write 8854 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
TypeError: messageManager is undefined context-menu.js:689:2
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:9:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:30:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:36:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:56:13
Неизвестное свойство «user-select».  Потерянное объявление. index.css:90:13
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:103:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:122:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:142:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:233:13
DOMException [SyntaxError: "An invalid or illegal string was specified"
code: 12
nsresult: 0x8053000c
location: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/data/popup/index.js:5] core.js:91
TypeError: can't access dead object tab-firefox.js:98:0

**Comment by inbasic** [comment]
@epson950 Try this debugging version https://www.dropbox.com/s/s2hytfy7332f84e/firefox.xpi?dl=0

I am interested in the new debugging log that will be printed above
```
DOMException [SyntaxError: "An invalid or illegal string was specified"
code: 12
nsresult: 0x8053000c
location: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/data/popup/index.js:5] core.js:91
```
after installation

**Comment by presnell72** [comment]
Inbasic, I removed the original notifier, and installed the xpi from above. No change in behavior / still broken. Thanks again for working this problem.

**Comment by inbasic** [comment]
@presnell72 you can also install the https://www.dropbox.com/s/s2hytfy7332f84e/firefox.xpi?dl=0 version and follow the steps to report the bug. I need to know what locale in what language has this illegal string in it.

**Comment by epson950** [comment]
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/chrome.manifest'.
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
Warning: attempting to write 8855 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
Warning: attempting to write 8854 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
TypeError: messageManager is undefined context-menu.js:689:2
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:9:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:30:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:36:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:56:13
Неизвестное свойство «user-select».  Потерянное объявление. index.css:90:13
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:103:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:122:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:142:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:233:13

**Comment by inbasic** [comment]
I removed the RU locale for now. This might have fixed the problem.

Install this version
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

Then restart your browser and let me know if it works.

**Comment by epson950** [comment]
Ну вот, и сюда санкции добрались :( Чем вам RU локаль помешала? Тем более это не помогло!
С русскими надо дружить! :)
It's not work!

**Comment by epson950** [comment]
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/chrome.manifest'.
Could not read chrome manifest 'file:///D:/PORTABLE/ff31esr/Firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
Warning: attempting to write 8855 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
Warning: attempting to write 8854 bytes to preference extensions.xpiState. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
TypeError: messageManager is undefined context-menu.js:689:2
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:9:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:30:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:36:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:56:13
Неизвестное свойство «user-select».  Потерянное объявление. index.css:90:13
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:103:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:122:11
Ошибка при парсинге значения «display».  Потерянное объявление. index.css:142:11
Неизвестное свойство «user-select».  Потерянное объявление. index.css:233:13
DOMException [SyntaxError: "An invalid or illegal string was specified"
code: 12
nsresult: 0x8053000c
location: resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/data/popup/index.js:5] core.js:91
TypeError: can't access dead object tab-firefox.js:98:0

**Comment by epson950** [comment]
It is necessary to look for not in the Russian locale, and in those changes which happened from version 0.5.8! In that version everything works!

**Comment by JohnnyGaloshes** [comment]
This new .xpi did not fix it, sorry. :(

**Comment by skyyan** [comment]
Same issue on FF 38.4.0. 
But the 0.5.8 works fine. thx

**Comment by presnell72** [comment]
Just FYI, I reverted back to 0.5.8 (FF 38.0 / Linux Mint) and that version still works. Thanks.

**Comment by epson950** [comment]
Please share version 0.5.8. Also prompt as to make that it wasn't updated?

**Comment by presnell72** [comment]
Yes, I set version 0.5.8 to not be automatically updated. 

For those looking for how to disable add-on updates (FF 38.0):
1) Go to Add-ons Manager
2) Right-click gmail notifier and select "Show More Information"
3) At the bottom, choose 'Off' for Automatic Updates

**Comment by epson950** [comment]
and where now to take version 0.5.8?

**Comment by presnell72** [comment]
epson950, you can get older versions here:

https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions/

Hover over the 0.5.8 row and you'll see the green "Add to Firefox" button.

**Comment by inbasic** [comment]
Guys please install this version
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

Now open error console and clear it. Disable and re-enable the extension to provide logs.

**Comment by presnell72** [comment]
inbasic, the last xpi seemed to fix all the problems I was having. Emails show up correctly in the popup window and the G icon takes me to gmail.

I still went ahead and grabbed the Browser Console logs for you:

Could not read chrome manifest 'file:///usr/lib/firefox/browser/extensions/%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D/chrome.manifest'.
1452260267287	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: locale
1452260267288	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: greasemonkey-user-script
1452260274481	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: locale
1452260274482	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: greasemonkey-user-script
TypeError: can't access dead object tab-firefox.js:98:0
Object {  } "popup_open_settings" sandbox.js:305
Object {  } "popup_open_inbox" sandbox.js:305
Object {  } "popup_archive" sandbox.js:305
Object {  } "popup_spam" sandbox.js:305
Object {  } "popup_trash" sandbox.js:305
Object {  } "popup_refresh" sandbox.js:305
Object {  } "popup_read_all" sandbox.js:305
TypeError: can't access dead object tab-firefox.js:98:0

**Comment by inbasic** [comment]
@presnell72 can you also click on the `Object { }` and take an screenshot of the right panel that opens up?

`Object { } "popup_open_inbox" sandbox.js:305` 

Based on this error, I assume that when you hover your mouse over the panel buttons (trash, refresh, ...), no translation appears, right?

**Comment by presnell72** [comment]
@inbasic hovering over the panel buttons just gives me the function name, such as "popup_open_inbox"

Here's the screenshot you asked for:

![notifier1](https://cloud.githubusercontent.com/assets/16525699/12221035/e1841376-b758-11e5-9bee-baf08bdbe7ec.jpg)

**Comment by inbasic** [comment]
@presnell72 have you this issue on `en` locale as well?

**Comment by presnell72** [comment]
Your last xpi fixed all problems. I have no issues. My locale is en.

**Comment by inbasic** [comment]
Perfect! Thanks for the confirmation.

**Comment by inbasic** [comment]
Version 0.6.1 is now submitted to AMO,
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/versions
