### ISSUE TITLE
Possible bug - Printing after installing the app

### ISSUE THREAD

**Issue by mnowax** [inbasic/ignotifier#381]
OS Windows 7 
Chrome Version: 47.0.2526.106 m
Version of App: 0.6.0

Details of issue: User has a Gmail tab open.  User then installs app.  User attempts to print using the print icon in Gmail - this fails by giving an "Invalid URL" page to the pop-up window.

Workaround: Once app is installed user closes all instances of Gmail, then opens a new tab for Gmail.  All functions appear to work correctly again.

Reasoning for issue:  I believe this is caused by a re-authentication when the extension is first installed.    I'm unsure if this is a true bug in the sense, but perhaps an automatic browser refresh would be useful when the extension is installed.

**Comment by inbasic** [comment]
I wasn't able to generate this bug. GN does not inject any script on the open tabs. It is very unlikely it can interfere with the Gmail UI. Can you regenerate the bug?

**Comment by mnowax** [comment]
I can no longer regenerate the bug in Chrome Version 48, so it must have been a minor bug with Chrome itself rather than the notifier.  Thanks for your help!

To clarify - I never thought it did, I just think it was reauthenticating a new session of Gmail when the extension was installed, leaving the current session( and tab ) invalid, but looking like it was still valid.
