### ISSUE TITLE
"Desktop notifications are now shown one by one to provide more details"

### ISSUE THREAD

**Issue by justanotheranonymoususer** [inbasic/ignotifier#382]
Can this new feature be turned off? Thanks.

**Comment by inbasic** [comment]
Why do you need this? The new versions of Firefox does not allow you to have long notifications. Firefox just cuts the long notification

**Comment by justanotheranonymoususer** [comment]
I have five email accounts, and more often than not I'm just interested in seeing which ones have unread emails, preferably with the title of the last unread email. It's a bummer to watch five notifications come and go.

**Comment by inbasic** [comment]
Why not just hovering your mouse over the toolbar button then?

**Comment by justanotheranonymoususer** [comment]
First, the tooltip doesn't show any additional information, such as the last email title.
Second, sometimes the tooltip becomes truncated, or doesn't work, or doesn't show an updated information. But those are different issues. I'll post about it when I'll stumble upon it again.

In any case, the new behavior is a regression, and I think that providing an option to disable it is the right thing to do.

**Comment by inbasic** [comment]
Thanks for the report. I added a new option under "Notifications" section

https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

**Comment by justanotheranonymoususer** [comment]
Awesome, thanks!
