### ISSUE TITLE
[Bug Report] Icon Position

### ISSUE THREAD

**Issue by waldens** [inbasic/ignotifier#383]
Check this gif, it's clear:
![Link](http://ww2.sinaimg.cn/large/d80a8e60gw1f0kl0amk3rg20ab0gmdzj.gif)

Already disable all other addon to prevent possible conflict.
Win7x64, Firefox43.0.2

**Comment by inbasic** [comment]
This must be a bug with Firefox's SDK. There is nothing I can do to fix this. Have you tried the latest Nightly to see if you can generate the bug there as well?

**Comment by waldens** [comment]
No, I didn't. That's fined. Not a big bug and already used to it. Thanks! :smile:

**Comment by inbasic** [comment]
ok so please update if you got anything new

**Comment by waldens** [comment]
@inbasic I tested it in Nightly just now. clean install, clean profile folder, and still have this problem. :(

❶ install a new Nightly and new profile
❷ open it, drag ignotifier's toolbar icon into menu
❸ open gmail website, log in
❹ send a mail to self
❺ close ff and reopen it
!❻ like the gif said...

GIF（778K）：
![GIF](http://ww2.sinaimg.cn/large/d80a8e60gw1f182efy3skg20m70hfnii.gif)

**Comment by inbasic** [comment]
When you do a restart, is the positioning issue resolved?

**Comment by waldens** [comment]
It's resolved temporarily after restart, but will definitely appear again once customize FF like above (or other ways I haven't noticed, not sure accurate trigger conditions). and the test case above can be 100% reproduced. @inbasic
