### ISSUE TITLE
Where did the toolbar panel go?

### ISSUE THREAD

**Issue by exekutive** [inbasic/ignotifier#385]
I just updated from v 0.2.2 to 0.6.2.
I used to click the toolbar icon to get a list of the emails in my inbox, compose new email etc.
Now when I click the toolbar button, it just opens the Gmail website in a new tab.
What happened?

**Comment by exekutive** [comment]
I was also able to move messages into folders, but I can't find that option now.

**Comment by inbasic** [comment]
What is the color of the toolbar button?

**Comment by exekutive** [comment]
The button is the color I chose for it: Blue for "no unread"

**Comment by exekutive** [comment]
So, is this a bug, new feature, problem with my settings? ...

**Comment by inbasic** [comment]
So even when the toolbar button is red (the original color if GN when is logged-in and can access your account; basically when there is a badge number) you cannot see the panel?

if so please follow these steps:
1. Open error console (Ctrl + Shift +J)
2. Clear the console
3. Disable and re-enable the notifier from add-on manager.
4. Wait for the notifier to fetch unread emails.
5. When there is a badge number, click on the toolbar button.

Is there any new error appearing in the console?

**Comment by exekutive** [comment]
I'm so sorry. I just realized that I thought your addon was a different one of very similar name!
I do have one suggestion for a improvement though. In addition to being able to delete, archive and mark emails as read, it would be nice to be able to move them to a folder.  Thanks for your time.
