### ISSUE TITLE
0.6.2 NG Tried Going Back to 0.6.1.1 Now That is Not Working

### ISSUE THREAD

**Issue by bob603** [inbasic/ignotifier#387]
Firefox 44.0.2 Windows10 64-bit

After setting up all email accounts and restarting I can see them when I mouseover, however if I right-click account it opens gmail webpage. Doesn't seem to remember account.

**Comment by inbasic** [comment]
Seems like GN cannot register a right click listener. Please  make sure you are on the latest release. Now restart your browser. Open error console (Ctrl + Shift +J). Clear the console and disable and re-enable the notifier and see if any error appears in the console.

**Comment by bob603** [comment]
I think I may have found the trouble. I had noticed that Firefox had
history privacy setting set to "remember history" and I had changed it to
not remember history. After doing this, it breaks ignotifier even in fresh
install, because I tried creating a new profile and reinstalling, etc. I
solved it for now by opting to set the history privacy setting to "use
custom settings for history" and ticking the clear history when firefox
closes. Everything seems back to normal. Maybe you can try in your labs.

On Sun, Feb 21, 2016 at 3:01 AM, InBasic <notifications@github.com> wrote:

> Seems like GN cannot register a right click listener. Please make sure you
> are on the latest release. Now restart your browser. Open error console
> (Ctrl + Shift +J). Clear the console and disable and re-enable the notifier
> and see if any error appears in the console.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inbasic/ignotifier/issues/387#issuecomment-186773574>.
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~

**Comment by bob603** [comment]
Okay, scratch the last thing I said, apparently that didn't fix it, because
I lost all of my accounts again and needed to setup ig again.

I ran the console and disabled/enabled the addon and all I get is:
Could not read chrome manifest
'file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/chrome.manifest'.

I'm going to try and set back to remember history and see it that works for
the meanwhile.


On Sun, Feb 21, 2016 at 3:01 AM, InBasic <notifications@github.com> wrote:

> Seems like GN cannot register a right click listener. Please make sure you
> are on the latest release. Now restart your browser. Open error console
> (Ctrl + Shift +J). Clear the console and disable and re-enable the notifier
> and see if any error appears in the console.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inbasic/ignotifier/issues/387#issuecomment-186773574>.
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~

**Comment by bob603** [comment]
I tried reverting back to remember history and setup accounts again. Closed
Firefox and lost all accounts again. So now it doesn't matter where history
privacy is set, it loses all accounts when Firefox is closed.

On Sun, Feb 21, 2016 at 8:13 AM, Rob Grant <robgrant65@gmail.com> wrote:

> Okay, scratch the last thing I said, apparently that didn't fix it,
> because I lost all of my accounts again and needed to setup ig again.
>
> I ran the console and disabled/enabled the addon and all I get is:
> Could not read chrome manifest
> 'file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/chrome.manifest'.
>
> I'm going to try and set back to remember history and see it that works
> for the meanwhile.
>
>
> On Sun, Feb 21, 2016 at 3:01 AM, InBasic <notifications@github.com> wrote:
>
>> Seems like GN cannot register a right click listener. Please make sure
>> you are on the latest release. Now restart your browser. Open error console
>> (Ctrl + Shift +J). Clear the console and disable and re-enable the notifier
>> and see if any error appears in the console.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/inbasic/ignotifier/issues/387#issuecomment-186773574>
>> .
>>
>
>
>
> --
> ~~~~~~~~~~~~~~~~~
> robgrant65@gmail.com
> ~~~~~~~~~~~~~~~~~
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~

**Comment by inbasic** [comment]
> Closed Firefox and lost all accounts again

This has nothing to do with GN. GN uses the current session of your browser to fetch unread emails. Basically the notifier just fetches RSS feeds. That's it. You need to solve other issues before dealing with GN related issues. That's the reason I always suggest reporting bugs on a clean profile.

**Comment by bob603** [comment]
That GN doesn't remember accounts, has nothing to do with GN? What else
would control this? Can you explain what you mean by reporting bugs on a
clean profile?

On Sun, Feb 21, 2016 at 9:56 AM, InBasic <notifications@github.com> wrote:

> Closed Firefox and lost all accounts again
>
> This has nothing to do with GN. GN uses the current session of your
> browser to fetch unread emails. Basically the notifier just fetches RSS
> feeds. That's it. You need to solve other issues before dealing with GN
> related issues. That's the reason I always suggest reporting bugs on a
> clean profile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inbasic/ignotifier/issues/387#issuecomment-186834937>.
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~

**Comment by inbasic** [comment]
Read FAQ 6, http://add0n.com/gmail-notifier.html

For the notifier to work, all the feeds need be accessible.

**Comment by bob603** [comment]
Yes, I have that all setup. I've been using this long time already. I enter
inbox for all accounts.


​

On Sun, Feb 21, 2016 at 10:06 AM, InBasic <notifications@github.com> wrote:

> Read FAQ 6, http://add0n.com/gmail-notifier.html
>
> For the notifier to work, all the feeds need be accessible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inbasic/ignotifier/issues/387#issuecomment-186836802>.
>



-- 
~~~~~~~~~~~~~~~~~
robgrant65@gmail.com
~~~~~~~~~~~~~~~~~
