### ISSUE TITLE
Feature request: Show a list of logged-in accounts on right click (Chrome)

### ISSUE THREAD

**Issue by nitrobg** [inbasic/ignotifier#391]
I know the Firefox version of the addon shows a list of the logged-in accounts when the user right clicks on the toolbar icon. When one of the accounts is clicked, the browser loads this account's page.
Is it possible to port this feature to Chrome as well?

**Comment by inbasic** [comment]
Yes! with the new improvements on Chrome's context menu API, we can have this on version 0.6.3
You can try the dev version now, https://github.com/inbasic/ignotifier/tree/beta/builds/packed

Thanks for the report.
