### ISSUE TITLE
Authentication required spam

### ISSUE THREAD

**Issue by Betrayed** [inbasic/ignotifier#392]
Getting this window ![mdnyo08](https://cloud.githubusercontent.com/assets/15057385/13761937/5929b17e-ea44-11e5-9e48-7233fedcdcb1.png)
 every time GN checks the inbox (every 15s). Filling the data in wont make an difference, nor does the page I'm currently on. Logged into 4 accounts, and this started happening with latest version. Downgrading did not fix the issue.

**Comment by inbasic** [comment]
Is this on Firefox or Chrome?

**Comment by Betrayed** [comment]
Firefox 45.0.1

**Comment by inbasic** [comment]
Can you try the notifier on a clean profile? http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

Maybe it is conflicting with another extension.

**Comment by Betrayed** [comment]
Yup, worked fine with clean profile, which gave me an idea that Googles cookies might've been somehow bit messed up. Cleared all of them and relogged, enabled addon, restarted FF for good measure, no more spam.
