### ISSUE TITLE
audio failing

### ISSUE THREAD

**Issue by meoso** [inbasic/ignotifier#394]
I'm not getting audio anymore.  This has been true for awhile, but unsure when it started.  Using Firefox 45 as of now. OS is Linux. Tried with mp3 and wav. Other add-ons are properly launching audio. `ignotifier 0.6.2`

**Comment by inbasic** [comment]
Lets see if you get an error when sound is playing. Open error console (Ctrl + Shift +J). Clear it and force refresh the notifier when there is an unread email in your Gmail account (middle click on the button or right click and press refresh). Do you get a new error in the console?

**Comment by meoso** [comment]
looks like it only show `ok` for label, nothing about sound.

all console tabs were turned on, you see here 1 gmail notifier update, two errors from another plugin, then gmail notifier repeated.  I'm using the character "♪" as a label, but it have tested and such is not the issue as any label fails.
```
GET XHR  https://mail.google.com/mail/u/0/feed/atom/%E2%99%AA [HTTP/2.0 200 OK 175ms]

Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. d1886.js:26:45628
Handler function NM_observeActivity threw an exception: TypeError: aChannel.loadInfo is null
Stack: NetworkMonitor.prototype._createNetworkEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:841:1
NM__onRequestHeader@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:905:1
NM_observeActivity@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/network-monitor.js:680:7
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:87:14
Line: 841, column: 1 DevToolsUtils.js:63:0

Handler function threw an exception: TypeError: aChannel.loadInfo is null
Stack: ServerLoggingListener<._matchRequest@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/server-logger.js:238:1
ServerLoggingListener<.onExamineResponse<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/webconsole/server-logger.js:196:10
makeInfallible/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://devtools/shared/DevToolsUtils.js:87:14
Line: 238, column: 1 DevToolsUtils.js:63:0

GET XHR  https://mail.google.com/mail/u/0/feed/atom/%E2%99%AA [HTTP/2.0 200 OK 227ms]
```

**Comment by Imold** [comment]
Is autoplay disabled? If so this is a dup of #598, the workaround is to open the settings page, then open "Page Info"( Ctrl+i ), go to the Permissions tab, find "Autoplay" uncheck "Use Default", and select "Allow Audio and Video".

**Comment by meoso** [comment]
not using ignotifier anymore, so i'll just close the ticket untested.
