### ISSUE TITLE
High DPI makes lower buttons disappear.

### ISSUE THREAD

**Issue by ChazZeromus** [inbasic/ignotifier#395]
Using the extension for Chrome (49.0.2623.87 m) on a surface pro 4 (2736x1824), when I get notifications all the bottom row buttons disappear, so I'm not able to mark as read or use any of the other buttons.

**Comment by inbasic** [comment]
I wish there was a way to generate this bug. I only have access to a Mac PC with High DPI and I am not able to re-generate this bug.

Can you submit an screenshot of the bug?

**Comment by ChazZeromus** [comment]
![untitled](https://cloud.githubusercontent.com/assets/2003232/14034807/2e196e1e-f1fd-11e5-8a8c-df0adbc76de2.jpg)


Hope this helps!

**Comment by inbasic** [comment]
Have you altered Chrome's zoom settings?
chrome://settings/search#zoom

It seems the notifier cannot expand Chrome's panel enough to fit the content. Try to reduce the dimensions of the panel in the settings to 500px and see if it helps
