### ISSUE TITLE
I have more than 4 accounts problem.

### ISSUE THREAD

**Issue by jin8864** [inbasic/ignotifier#396]
Hello.
I have more than 4 gmail accounts and found the article #143. However, it showed only 4th and 5th accounts when I tried it. I think that is does not work anymore because I found FAQ no.5 also has old information. Please let me know what I should do to figure it out.
Thanks for great add-on!

**Comment by inbasic** [comment]
Thanks. I just updated FAQ 12, http://add0n.com/gmail-notifier.html
