### ISSUE TITLE
Firefox: middle click opens two tabs

### ISSUE THREAD

**Issue by trlkly** [inbasic/ignotifier#397]
STEPS TO REPRODUCE:
1. Install ignotifier in Firefox.
2. Set up email.
3. Middle-click on link in email.

EXPECTED RESULTS:
One tab is opened.

ACTUAL RESULTS:
Two tabs are opened.

NOTES:
When I middle click on a link in an email, I always wind up with two tabs instead of just one. My guess is that two events are firing, when it should only be one. Left click works properly, and only opens one tab. (But I am used to middle-clicking.)

**Comment by inbasic** [comment]
Thanks for the report. It is now fixed on the dev channel
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

To try you can download the XPI and drop it into your Firefox.

**Comment by trlkly** [comment]
I confirm that the fix resolves the issue.
