### ISSUE TITLE
mouseover in tray at bottom does not display badge number

### ISSUE THREAD

**Issue by imperial6310** [inbasic/ignotifier#399]
when mousing over a gmail email address in the tray icon  at bottom of screen, the badge number is missing next to the email name.  I have multiple gmails and it only happens to the longer email addresses. I think you may have to lengthen the display screen when using the tray icon mouseover to accommodate longer gmail names so the badge number can be viewed next to the gmail address.

**Comment by imperial6310** [comment]
From what i can tell, the top email address in the tray icon always receives the badge number while the email address underneath it is not during mouseover.

**Comment by inbasic** [comment]
The tooltip text over tray icon accepts limited number of chars. As far as I know there is no workaround for this.

**Comment by imperial6310** [comment]
if you have a limited number of characters in the tray, can you please remove the word notifier, to help free us some characters, please..

**Comment by imperial6310** [comment]
another excellent option would be to create a setting to allow us to abbreviate or shorten the email address (alternate email name) so as to allow more data to be viewed in the mouse-over tray field.
Please advise.

**Comment by inbasic** [comment]
So in the next release we will have two enhancements in the tray's tooltip text
1. If length is long, no app title is added to the tooltip
2. If still tooltip is long @mail-provider.domain will be stripped from all email addresses

You can try the beta version now:
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true
Download the XPI and load it in about:Debugging tab

**Comment by imperial6310** [comment]
yes that works perfectly for us.
thank you.

Larry
