### ISSUE TITLE
Firefox 45 doesn't terminate correctly when exiting from the extension setting page with the "power" button" in the hamburger menu

### ISSUE THREAD

**Issue by LL25255252** [inbasic/ignotifier#400]
Steps to reproduce:

Open a new/clean firefox profile

install Gmail™ Notifier (restartless)
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/ 

goto to the extension setting page at:
resource://jid0-gjwrpchs3ugt7xydvqvk4dqk8ls-at-jetpack/data/options/index.html

Exit Firefox the right way by using the power button in the hamburger menu (don't just close the window by clicking the "x" button at the top of the window).

The browser window will then be closed but firefox process will hang for 1 minute and then it will end with the crash reporter window.

extension version - (0.6.2)
Firefox 45.0.02
Win 7 x64

BTW - I've recently found the same bug on uBlock Origin addon. He fixed it today with this code :
https://github.com/gorhill/uBlock/commit/d34d47032de73f86528e9bbabe6f397aea5caa22

**Comment by inbasic** [comment]
Thanks for the report. It is now fixed on the latest dev version
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true
