### ISSUE TITLE
Request about opening new tabs

### ISSUE THREAD

**Issue by THTHTHTHTHTH** [inbasic/ignotifier#409]
Would it be possible to add an option that enables a new gmail tab to be opened every time the notifier icon is clicked regardless if there are already gmail tabs open? Sometimes I have a gmail tab open already in my browser but I don't want that one to be selected when I click the notifier icon. With that feature the notifier would be perfect for me.

**Comment by inbasic** [comment]
Sure, we will have this on the next release. Thanks for the suggestion

**Comment by THTHTHTHTHTH** [comment]
Thanks!

2016-09-14 9:00 GMT+03:00 InBasic <notifications@github.com>:
