### ISSUE TITLE
No Taskbar icon

### ISSUE THREAD

**Issue by lcdnz** [inbasic/ignotifier#411]
I've installed GN from the chrome store on Windows 7 Enterprise N, and the icon etc. is working fine within Chrome, but there is no icon in the windows taskbar, which is the main feature that I'm after.
![nognicon](https://cloud.githubusercontent.com/assets/20806437/17351543/b47153ee-5983-11e6-8fe8-de5286b9cd1a.png)

**Comment by inbasic** [comment]
This is Firefox only feature. Chrome API does not allow this
