### ISSUE TITLE
Cannot mark as read when there are similar unread messages

### ISSUE THREAD

**Issue by AndrewFFF** [inbasic/ignotifier#412]
Firefox 48 (and previous versions, too).

I have two messages with the same topic and sender (but different Message-ID's) in my inbox. I click 'Mark As Read', and the addon marks one of them as read. I click 'Mark As Read' again and expect the addon to mark another message as read, but nothing happens.

**Comment by trurl123** [comment]
I have the same in Google Chrome. Note that I disabled message groups in Gmail.

**Comment by inbasic** [comment]
As it has mentioned in the FAQs page, the notifier cannot detect ids when message grouping is turned off. Basically there is no per message id in the provided XML file by Gmail's feed, just group ids.
