### ISSUE TITLE
Don't hide popup when an email body link is clicked to open it in a background tab or a new window

### ISSUE THREAD

**Issue by tophf** [inbasic/ignotifier#415]
There are several standard methods of opening links in a background tab (middlebutton click, Ctrl-click) or a new window (Shift-click, context menu "Open in a new window"). These are used in a typical scenario of opening multiple tabs while reading current tab. Or when reading an email with many links.

Currently ignotifier unconditionally [closes the popup](https://github.com/inbasic/ignotifier/blob/64cb28ed954ee61b8981f305c2fbb67d88483200/src/lib/common.js#L535), which is bad for the mentioned scenario because it requires reopening of the popup as many times as there are links of interest. It doesn't respect the standard keyboard modifiers mentioned above as well as Middleclick (it no longer triggers `click` event in modern Chrome).

**Comment by tophf** [comment]
I've fixed this locally:

* popup/index.js:

  ~~~js
function opener
..................
      background.send("open", {
        url: link,
        background: e.button == 1 || e.ctrlKey && !e.shiftKey && !e.altKey && !e.metaKey
      });
..................
qs("iframe").contentDocument.addEventListener("auxclick", function(e) {
      if (e.button == 1 && e.target.closest('a'))
        opener(e);
});
~~~

  See [crbug#625847](https://bugs.chromium.org/p/chromium/issues/detail?id=625847) for `auxclick` details.

* common.js:

  ~~~js
app.popup.receive('open', function (link) {
  //app.popup.hide();
  if (link) {
    if (typeof link == 'object')
      open(link.url, link.background);
    else
      open(link);
  }
});
~~~

**Comment by inbasic** [comment]
Thanks for the report. Can you push a pull request to fix this?

**Comment by tophf** [comment]
I posted my solution for you to use as a starting point because I'm it's not complete (no Shift-click) and I don't know if it could break things.

**Comment by inbasic** [comment]
Thanks for the report. We will support Ctrl/Command+Click and middle-click for opening in background page. Shift+click is not yet supported though.

**Comment by auipga** [comment]
Unfortunately this doesn't work for me on Linux/Gnome
