### ISSUE TITLE
Request: use Firefox's notifications, for GNotifier compatibility

### ISSUE THREAD

**Issue by AndydeCleyre** [inbasic/ignotifier#417]
Hi,

Thanks for this addon!

It seems to use its own notification widgets. If it instead used Firefox's built-in notifications, it would be possible for a user to turn them native with the independent [GNotifier](https://github.com/mkiol/GNotifier) addon, which can make all Firefox notifications native to the user's OS.

**Comment by inbasic** [comment]
Gmail Notifier uses the built-in SDK notification module; https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/notifications

**Comment by AndydeCleyre** [comment]
Aaaand today, this works.

firefox 49.0
ignotifier 0.6.5
gnotifier 1.9.7
