### ISSUE TITLE
Click on notification doesn't open email.

### ISSUE THREAD

**Issue by danielquijada** [inbasic/ignotifier#427]
I'm not sure if this is a bug or if it's just not added as a feature, but when I recieve an email notification and click on said notification, it does absolutely nothing.

Shouldn't it open email on my inbox o at least the big popup that comes up when I click on the tray icon?

**Comment by inbasic** [comment]
What is your browser? In Chrome version, there is no permission to open the popup by pressing the notification

**Comment by danielquijada** [comment]
Oh, it is Chrome.

Will this be fixed (or made so it opens the inbox or something) or it's just a GC limitation?

**Comment by inbasic** [comment]
Yes, Chrome does not allow extensions to open panel. But we can have it open the inbox at least. Will have this on the next release.
