### ISSUE TITLE
Trailing comma in object at 22:5

### ISSUE THREAD

**Issue by soad1982** [inbasic/ignotifier#428]
Hi,

I just clone this repository and got this error:

npm WARN Failed to parse json
npm WARN Trailing comma in object at 22:5
npm WARN     }
npm WARN     ^
npm WARN File: /home/XXXX/ignotifier/package.json
npm WARN ignotifier No description
npm WARN ignotifier No repository field.
npm WARN ignotifier No README data
npm WARN ignotifier No license field.

I edited the package.json file and at the end here was an extra ,

 "jpm": "*" , 

I just deleted the , at the end and the npm command started working.

**Comment by inbasic** [comment]
Thanks for the report. It is fixed now
