### ISSUE TITLE
Getting emails from Private Window

### ISSUE THREAD

**Issue by altrisi** [inbasic/ignotifier#430]
If you are in a private window, you only can get emails from the normal windows. Can you please add an option (or by default) to allow gmail notifier getting emails from the session in the private window?
Thanks.

**Comment by inbasic** [comment]
I managed to support private mode in the Firefox version. You can try the latest dev version here: https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true

Download the XPI, then open "about:debugging" in a browser tab and point the "Load Temporary Add-on" to this XPI file

Let me know if you have found a bug related to this implementation.
