### ISSUE TITLE
Can't delete on my main account, can delete on other accounts

### ISSUE THREAD

**Issue by Chromelon** [inbasic/ignotifier#433]
When I try to delete an email, I get
"TypeError: target.closest(...) is null"

Specifically

// Link opener for html
function opener (e) {
  e.preventDefault();
  e.stopPropagation();
  var target = e.originalTarget || e.target;

  var link = target.closest('a').href || target.src || target.href; //This line is reporting back null when I hit a button on my main account

  if (link) {
    background.send("open", {
      link: link,
      button: e.button,
      ctrlKey: e.ctrlKey,
      shiftKey: e.shiftKey,
      altKey: e.altKey,
      metaKey: e.metaKey
    });
  }
}

**Comment by Chromelon** [comment]
Edit: It seems that it doesn't support deleting when the account is linked to Inbox by Gmail. Any way around this?

**Comment by inbasic** [comment]
Unfortunetly not. When redirection to inbox is enabled, Google redirects all Gmail requests to inbox and hence action buttons are not working anymore.
