### ISSUE TITLE
Notifier not displayed on Nightly

### ISSUE THREAD

**Issue by qzgy** [inbasic/ignotifier#436]
The notifier is not being displayed anywhere with the plugin installed on the newest nightly build.

**Comment by floppyrom** [comment]
Same problem on Nightly 53.0a1 (2016-11-25) (64-bit)

**Comment by Matth7878** [comment]
I think it's related to [for-each-in loop being removed](https://www.fxsitecompat.com/en-CA/docs/2015/for-each-in-loop-support-will-be-removed/)
See also [Bugzilla Bug 1293305 - Disable non-standard for-each on nightly-only ](https://bugzilla.mozilla.org/show_bug.cgi?id=1293305)

**Comment by Matth7878** [comment]
Do not know how to push to github but to fix it it is what I did : 
- opened xpi to edit app.js (in lib\wrapper\firefox)
- replaced line 232 : "for **each** (var tab **in** tbs) {" with "for (var tab **of** tbs) {"
- same for line 476 : "for **each** (var tab **in** tbs) {" with "for (var tab **of** tbs) {"

**Comment by inbasic** [comment]
Thanks for the report. Version 0.7.0 which is already submitted for review fixes this issue.
