### ISSUE TITLE
Conflicted with other addons

### ISSUE THREAD

**Issue by yaroslavcat** [inbasic/ignotifier#437]
Sound notifications and systray icon doesn't work if use with [Доступ к Рутрекеру](https://addons.mozilla.org/ru/firefox/addon/%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF-%D0%BA-%D1%80%D1%83%D1%82%D1%80%D0%B5%D0%BA%D0%B5%D1%80%D1%83/) and/or [AdBlocker for YouTube](https://addons.mozilla.org/en-US/firefox/addon/adblock-for-youtube/?src=search).
Tested in Firefox_50.0.2(x64) on a clean profile.
How can i eliminate this problem?

**Comment by inbasic** [comment]
Can you confirm this on a clean profile?

**Comment by inbasic** [comment]
http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by yaroslavcat** [comment]
Yes, it does not eliminate the problem. Only disabling an 2 extension and restart a browser.
