### ISSUE TITLE
[Bug] In some e-mail, not show all images in preview

### ISSUE THREAD

**Issue by kovacsattila-hun** [inbasic/ignotifier#441]
In some e-mail, not show all images in preview.

Examples:

![1](https://cloud.githubusercontent.com/assets/19515287/21521278/c778d610-ccfb-11e6-889e-92e14ba4a812.png)
![2](https://cloud.githubusercontent.com/assets/19515287/21521279/c77987d6-ccfb-11e6-85c0-348d2d2be12e.png)

![3](https://cloud.githubusercontent.com/assets/19515287/21527284/654a8cc0-cd2a-11e6-9935-ebb5af965a31.png)

OS: Windows 10 x64
Browser: Google Chrome 55 x64 (Windows)
Extension:  Gmail™ Notifier 0.6.9

Please fix! Thx.

**Comment by inbasic** [comment]
Can you forward an email with this issue to inb[.]cor[at]gmail[.]com
