### ISSUE TITLE
Does not log in when privacy.firstparty.isolate is enabled

### ISSUE THREAD

**Issue by MikkCZ** [inbasic/ignotifier#444]
I have tried to enable **privacy.firstparty.isolate**, but seems it has broken Gmail notifier. After setting this preference to **true**, the notifier only asks me to log in, despite I have done it already. Looks like the isolation cuts the add-on off the information it needs.

**Comment by inbasic** [comment]
The notifier needs to access to gmail feeds through background XMLHttpRequests. If this preference limits these type of accesses then there is no way for the notifier to check unread emails. You can check the background requests from browser console and see if these requests are failing or not

**Comment by MikkCZ** [comment]
I see some Unathorized XHR to mail.google.com in the browser console, so I guess turning this preference on blocks access to cookies from the add-on. Would it be possible to use Google auth from the add-on independently on the login in the browser itself? It would help me personally in another way too, as I am logged to multiple Google account, but would like to get notifications only from one of them.

**Comment by MikkCZ** [comment]
This will probably get resolved by packing as WebExt #460. If not, it's probably an issue in Firefox itself, or even an expected behavior.
