### ISSUE TITLE
JS notification kills audio & video

### ISSUE THREAD

**Issue by KeyWeeUsr** [inbasic/ignotifier#450]
It's probably very hard to replicate, so I'll first state my add-ons if there's a chance of collisions between them:

* uBlock Origin
* AdBlock Plus
* Mind the Time
* Privacy badger
* Greasemonkey
* uMatrix

I turned each of them off separately while having the gmail notifications on and after from 10min to 2h there was always a JS notification popup that stopped e.g. a youtube video (and basically every audio & video) in Firefox until I restarted the browser.

Since I turned off the gmail add-on, I haven't experienced any video crash yet. I really liked the add-on, any ideas how to fix it? Or maybe an option to disable JS notifications would be nice - personally I just care about some small reminder I have new mail and that's visible even on the add-on's icon. ^_^

**Comment by inbasic** [comment]
I am not sure how this add-on can crash videos! anyhow there are different options to turn the desktop and alert sound off in the options page.

**Comment by KeyWeeUsr** [comment]
The add-on didn't. The _notification_ this add-on uses/used did. I turned it on and it happily stopped playing audio+video.
