### ISSUE TITLE
I have 5 gmail accounts I would like notified on

### ISSUE THREAD

**Issue by mrdblackdbr** [inbasic/ignotifier#452]
I wonder if you can help me,

I have 5 gmail accounts linked to my Opera browser that are connected to my primary gmail account that I would like to get connected to the notifier. No matter what I do, I can only get 4 accounts to be connected to the notifier.

TIA

**Comment by inbasic** [comment]
For the last one use the feed section. Use `https://mail.google.com/mail/u/4/feed/atom`

**Comment by mrdblackdbr** [comment]
I am sorry.

For me as soon as I try that the other accounts are disconnected. Only the
5th account remains.

**Comment by inbasic** [comment]
I forgot to mention you need to insert label `inbox` in the other fields. So label `inbox` for all known account and that feed URL for the 5th account in the feeds section.

**Comment by mrdblackdbr** [comment]
Worked!

Thanks.

**Comment by ingber** [comment]
This worked for me too.
