### ISSUE TITLE
[Feature Request] Show system tray icon when using the Chrome Extension

### ISSUE THREAD

**Issue by cganchev** [inbasic/ignotifier#453]
The Firefox Add-on shows an icon in the Windows System Tray when there are unread messages, but the Chrome Extension doesn't have such feature.
I think that having the tray icon is much more useful than only the icon next to the Chrome address bar, which can't be seen while using other applications.
The Google Hangouts extension adds tray icon so it should not be impossible to add this in Notifier for Gmail.

Also it's not correct to have this in the description of the Chrome Extension:

Features:
...
6. Get unread message notifications on Windows taskbar notification area (system tray)

**Comment by inbasic** [comment]
It is not possible. See http://stackoverflow.com/questions/38757348/system-tray-icon-for-chrome-extension

> 6. Get unread message notifications on Windows taskbar notification area (system tray)

Thanks I'll remove this
