### ISSUE TITLE
Gmail notifier doesn't remember the password

### ISSUE THREAD

**Issue by rypz79** [inbasic/ignotifier#458]
Hi,

I need to login to gmail every FX session.
When I refresh FX (clean install) it does work so there is a collision with my of the other extensions or FX preferences but which ?
any other suggestions how to fix it while staying in my current FX settings ?

Many Thanks
Roey

**Comment by Taurean75** [comment]
This add-on doesn't store passwords. Your problem sounds like a cookies issue. Perhaps you're blocking cookies...?

**Comment by rypz79** [comment]
Yes it was a cookie problem.
Thank you
