### ISSUE TITLE
Pack as a WebExtension for Firefox

### ISSUE THREAD

**Issue by MikkCZ** [inbasic/ignotifier#460]
Starting Firefox 57, Firefox will drop support for legacy add-ons a go with WebExtensions exclusively. It should be enough to just repack the Chrome add-on version for Firefox, if all used APIs are already implemented in Firefox.

@inbasic If you would like to help with testing, feel free to reach out to me.

**Comment by Taurean75** [comment]
Please let us know if you're going to convert this into a WebExtension.

**Comment by Manishearth** [comment]
I used the foxify Chrome addon extension (lets you install directly from the chrome web store). The directly converted addon did not work and the automated validation had these issues:

![screen shot 2017-08-02 at 15 31 46](https://user-images.githubusercontent.com/1617736/28897884-c4759222-7797-11e7-8ff4-679161d98d17.png)

**Comment by Taurean75** [comment]
The developer said that this WILL be ported to a WebExtension!

**Comment by corgrath** [comment]
I am using Firefox Developer Edition, which just became Quantum.

What's the best way to get notified when Gmail Notifier gets WebExtension-ified?

**Comment by Matth7878** [comment]
Personally I migrated to another web extension which does what I needed. Sadly I think this one is dead. :-\

**Comment by ocombe** [comment]
@Matth7878 which one did you use?

**Comment by Matth7878** [comment]
@ocombe GMail Checker Simple by G. Sándor

**Comment by EchoDev** [comment]
You can also give Checker Plus for Gmail a try, it's similar to Gmail notifier

https://addons.mozilla.org/firefox/addon/checker-plus-gmail/

**Comment by inbasic** [comment]
Gmail Notifier is now compatible with FF 57. The WebExtension is in the developer channel. Please give it a try and report bugs!
https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/#beta-channel

**Comment by ocombe** [comment]
Awesome, it works perfectly for me

**Comment by inbasic** [comment]
The only function that is removed is the tray icon for Windows OS. We might have this back later. Not at least until the new WebExtension is stable.

**Comment by EchoDev** [comment]
Also the setting are not migrated from legacy to webextension addon, correct?

Other than that it seems to work perfectly fine for me.

**Comment by EchoDev** [comment]
Also a small note:

If you don't accept third party cookies you need to make an exception for "https://mail.google.com" else the addon will not work.

**Comment by inbasic** [comment]
> Also the setting are not migrated from legacy to webextension addon, correct?

True!

**Comment by inbasic** [comment]
> Also a small note

Please add this note into the FAQs page under the review section. This might help FF users.
http://add0n.com/gmail-notifier.html

**Comment by MikkCZ** [comment]
I see this has been already done.

**Comment by FetchFast** [comment]
How does this affect the extension when used with Containers?
