### ISSUE TITLE
Cannot open 2nd Gmail account from popup window

### ISSUE THREAD

**Issue by mumeiyamibito** [inbasic/ignotifier#469]
I try to open a mail which received 2nd account from popup window, but this app opened 1st account Gmail.

How do I open 2nd Gmail account from popup window?

Vivaldi 64bit Ver. 1.11.917.39 on LinuxMint.

**Comment by inbasic** [comment]
right-click on the toolbar and select the account from the context menu. You can also use the popup window if there is an unread email in the second account
