### ISSUE TITLE
Toolbar button behaviour keeps resetting [Chrome]

### ISSUE THREAD

**Issue by blackICE19240** [inbasic/ignotifier#472]
I have "Toolbar button behaviour" set to open gmail account in new tab but usually after I restart chrome, I click the gmail button and the preview panel opens (still shows as open gmail account in settings but I have to switch to preview emails and back for it to work again)

**Comment by inbasic** [comment]
Is this still an issue?

**Comment by blackICE19240** [comment]
That's funny, when i got the notification for the email about this I just thought the preview hadn't opened for a while and then saw what the email said. Thanks for replying anyway
