### ISSUE TITLE
[Feature] allow to ask the duration and remember when Custom for disable all notifications 

### ISSUE THREAD

**Issue by yfdyh000** [inbasic/ignotifier#475]
use `prompt` in `browser.tabs.executeScript`.
e.g. https://github.com/yfdyh000/Search-Site-WE/commit/bd9d58c715b44ae82bca1dff4e0c051bddda9f69#diff-f9b12bd72f40c9b8ed144484f0f12a5fR151

**Comment by yfdyh000** [comment]
And/or display the duration (in minutes) on the menu item.

**Comment by inbasic** [comment]
A custom time duration can be set in the options page. The default is 10 minutes. Using `prompt` is definitely an improvement over setting a default value but this `browser.tabs.executeScript` is not working if the user has an active privileged tab like add-on manager for instance.

**Comment by yfdyh000** [comment]
Perhaps a sequence in the option is more flexibility, like "5,10,15,30,60,120,300" min.

**Comment by inbasic** [comment]
since we already have a few predefined time periods in the context menu, I would say let's allow users to define whatever period they need.
![screen shot 2017-10-12 at 5 10 43 pm](https://user-images.githubusercontent.com/351062/31499081-972b9256-af70-11e7-9670-57f957d3bf71.png)

**Comment by yfdyh000** [comment]
I know it, but maybe a sequence rather than just a custom value is more flexible.

**Comment by inbasic** [comment]
![screen shot 2017-10-13 at 9 50 45 am](https://user-images.githubusercontent.com/351062/31532832-67e8356c-affc-11e7-89e6-d96b1ad67c3c.png)
