### ISSUE TITLE
[WebExtension beta]Gmail Notifier does not seem to remember the toolbar button behaviour

### ISSUE THREAD

**Issue by EchoDev** [inbasic/ignotifier#476]
I have the "Toolbar button behaviour" set to "Open Gmail account if only one account is logged-in".

For some reason on a restart of the browser the option reset back to the email preview option but in the options menu itself it still shows as "Open Gmail account if only one account is logged-in".

On a restart of the browser I have to manually reset the option to open gmail account before it starts working like that again.

![gmailnotifier](https://user-images.githubusercontent.com/3149302/31543466-76243850-b016-11e7-8c25-ff8016ab4e6d.jpg)

Option set to "Open Gmail account if only one account is logged-in" but the preview is still opening.

Step by step reproduction

1. Set Gmail notifier option "Toolbar button behaviour" to "Open Gmail account if only one account is logged-in".
2. Check if the button opens Gmail, it should work fine.
3. Restart the browser.
4. Press the Gmail button, email preview opens up instead of Gmail.

edit: Seems like the same issue happens on Chrome https://github.com/inbasic/ignotifier/issues/472

**Comment by inbasic** [comment]
Thanks for the report. It should be fixed on `0.8.0b3`

**Comment by KrzysztofJozefowicz** [comment]
Hi
Similar issue with toolbar option "show notification" (I suppose that is the right name as in my translated version says "Włącz powiadomienia" - show preview of email when new email arrives). When FF starts it is enabled (notifs are shown),when disabled state of the option is not saved after FF is restarted. ignotif v 0.8.1

**Comment by inbasic** [comment]
@KrzysztofJozefowicz this is not a bug. So the item in the right-click menu is to temporarily disable the notifications like when you are at a meeting. This option gets reset when the browser is restarted. If you want to permanently disable all the notifications use the options page and uncheck the following options

  + Display desktop notification for new emails
  + Play alert sound for new emails
