### ISSUE TITLE
[WebExtensions] User Defined Sound and Notification Balloon Bugs

### ISSUE THREAD

**Issue by Taurean75** [inbasic/ignotifier#477]
Hey...

User defined sound is not being saved across sessions. Also, clicking on the notification balloon opens up the primary account even when the email is for the secondary account.

Windows 10 x64

Thanks

**Comment by inbasic** [comment]
Is this on the latest beta version for Firefox?

**Comment by Taurean75** [comment]
Yes, I'm on b2.

**Comment by Taurean75** [comment]
The sound file bug is fixed in b4, but the other bug is still there.

**Comment by inbasic** [comment]
The other one is also fixed on https://github.com/inbasic/ignotifier/commit/33a4643637e8f50223530b9e66c1c2099037b3a3. It is still not being submitted to AMO though.

**Comment by inbasic** [comment]
Please reopen if you are still experiencing it after b5 release.
