### ISSUE TITLE
Version 0.8.0 opens preview panel instead of Gmail acount if addon monitors "unread" and not "inbox" label

### ISSUE THREAD

**Issue by blacklion** [inbasic/ignotifier#479]
I have only one Gmail account, but I changed "inbox" label to "unread" in settings («Receive notifications for the following labels and accounts: - Primary account (/mail/u/0/)») to receive notifications about all new mail.

I have «Toolbar: Toolbar button behaviour» set to «Open Gmail account if only one account is logged-in».

When I click on Toolbar Icon it shows preview panel, and doesn't open GMail, as configured. 

If I change monitored label back to «inbox», click on toolbar icon works as intended (open new Gmail tab or switch to opened one).

This is new for 0.8.0.

**Comment by blacklion** [comment]
Click on toolbar window woks as intended if there are no new mail at all (icon is grey), BTW.

**Comment by inbasic** [comment]
Thanks for the report. It is fixed on 
https://github.com/inbasic/ignotifier/commit/a7b95de180227a5f163360e5a771460c902d6f14
