### ISSUE TITLE
Pop-up unreadable

### ISSUE THREAD

**Issue by rbowser11** [inbasic/ignotifier#484]
For the last two updates to Firefox, the Gmail notifier hasn't worked the way it used to. Pictures speak louder, so I'm attaching a screenshot of what I see now when I click after getting notification of a new message. If I click the title of the email in the pop-up, a new tab will open, and I can read the message - but that's not the way the notifier is supposed to work, not the way it did before. Previously I could click the taskbar icon, get the pop-up, read, mark as read or discard right there without leaving the page I currently have open in a browser tab.

I'm on Firefox 56.0, which is the most recent version.

Here's what I see now when I click - more than half of the right side of the pop-up is blacked out. A familiar problem to anyone?

![gmail app broken](https://user-images.githubusercontent.com/33324151/32359377-ead6bdc2-c00a-11e7-8887-0bcca7ed8aae.jpg)

**Comment by inbasic** [comment]
This seems like a theme issue. Have you checked the extension on a clean profile?
http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by rbowser11** [comment]
hmmm, thanks for the reply and the link, but that looks very complicated for just trying to make one extension work. Bummer is that it's worked fine up until 2 Firefox versions back. I hate it when upgrades disintegrate things. -- Thanks anyway. 
RB 

----- Original Message -----

**Comment by rbowser11** [comment]
UPDATE: As of a few days ago, the Gmail Notifier started working again. When clicked, the full pop-up comes up without the blacked out portion as in my screenshot. And I can delete mail from that pop-up without opening Gmail in a new tab. All back to the way it was before. Looks like a developer caught up with the problem Firefox was having with the Notifier. Thank you, whoever you are.
