### ISSUE TITLE
Notifier on Chrome doesn't load properly

### ISSUE THREAD

**Issue by hiimcody1** [inbasic/ignotifier#489]
This has been happening intermittently since a recent update on version 0.8.2.

I will go to click the icon in Chrome and I get a placeholder screen instead of the actual email.
![image](https://user-images.githubusercontent.com/1010914/33161832-b1c53e82-cfeb-11e7-9c32-48d14903b04b.png)

**Comment by mars1an** [comment]
Similar problem on Opera 36.0.2130.80 at windows xp, and seting page.
![empty_cr](https://user-images.githubusercontent.com/5398750/34374243-2446b2b8-eaf1-11e7-9186-c0d360aa2213.png)

**Comment by inbasic** [comment]
@mars1an your Opera version is not supported anymore. Please try the extension on Opera 47.

**Comment by inbasic** [comment]
@hiimcody1 what is your Chrome version? Do you sill have the issue after 0.8.8 release?

**Comment by mars1an** [comment]
@inbasic thx for answer, but at work i'm using win xp and last supported Oera 36, can you give me link on last version Notifier for my browser version.
At home, on Ubuntu 17.10 and last version Opera, all perfect.

**Comment by inbasic** [comment]
Check https://github.com/inbasic/ignotifier/releases

**Comment by hiimcody1** [comment]
@inbasic It was the latest release build of Chrome, 63. I forget minor version. It seems sorted out now, however. We can close this out I reckon unless there's any specific tests or info you'd like from me.

**Comment by inbasic** [comment]
Perfect! btw, we now support labels and the star button (activate from the options page)
