### ISSUE TITLE
Delete and mark as read require periodic chrome restarts

### ISSUE THREAD

**Issue by qwarkys** [inbasic/ignotifier#491]
Requires a restart of chrome about once a day in order for delete and mark as read to work. Without the restart, the stop doing anything. Everything else works properly.  Using with chrome Version 63.0.3239.84 (Official Build) (64-bit).  

Problems started about a week ago.

**Comment by Makpoc** [comment]
I'm having the same issue with Firefox (Developer Edition) 58.0b11 (64-bit)

**Comment by inbasic** [comment]
@Makpoc even on 0.8.5 release? It is not yet released for Chrome so I havent marked this solved yet.

**Comment by Makpoc** [comment]
I've just downloaded 0.8.5 and it works, but as original issue mentions - it looks like it takes some time for the buttons to fail. I will report back tomorrow with the result.

**Comment by Makpoc** [comment]
After staying idle for 12+hours the delete and mark as read buttons are working fine on FF 58 with 0.8.5.
