### ISSUE TITLE
Mark as Read or Mark all as Read wont work in FireFox

### ISSUE THREAD

**Issue by WhiteWolfSix** [inbasic/ignotifier#492]
Hi, after latest upgrade **Mark as Read or Mark all as Read** stoped to work in FireFox 57.0.2. It gets **Action -> Fetch error**.

**Comment by DawnB2** [comment]
I have the same issue, except I don't get an error it just "thinks" for a second then nothing happens. For me the Trash button also doesn't work. it thinks then nothing. I have to go into Gmail itself to delete or Mark as read. I also have FireFox 57.0.2

**Comment by inbasic** [comment]
Are you sure you are using v0.8.5?

**Comment by DawnB2** [comment]
yes says v0.8.5

**Comment by inbasic** [comment]
Can you login with a dummy Gmail account and let me check a few things on your machine? Say with TeamViewer (I need like 10 ish minutes)

**Comment by DawnB2** [comment]
sure just give me the dummy account info

**Comment by inbasic** [comment]
Create a new profile in your FF and register a new Gmail account. Then give me access
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by DawnB2** [comment]
sorry I don't have to time to set up another Gmail account right now. I tested deleting with my desktop & it worked so I removed & reinstalled notifier on my laptop then tested both deleting & mark as read it works fine now (so far) for me.

**Comment by inbasic** [comment]
If it works there is no point on checking either!

**Comment by WhiteWolfSix** [comment]
Well, it still don't work for me. I deleted this Add-On, used CCleaner and installed it back, with the same result.

**Comment by DawnB2** [comment]
i agree if it stops working I will let you know, hopefully it OP can getting it working too

**Comment by DawnB2** [comment]
I also removed all my signed out accounts from gmail. I only have 1 account in my account list on gmail right now. I don't know if you have any or if that's even related.

**Comment by WhiteWolfSix** [comment]
I use one gmail account only at the moment.

**Comment by DawnB2** [comment]
hopefully inbasic can poke around & fix it

**Comment by inbasic** [comment]
If it is not working properly I need to check it on your system. So if you are willing to allow local access, follow https://github.com/inbasic/ignotifier/issues/492#issuecomment-351325180 and ping me!

**Comment by WhiteWolfSix** [comment]
I also tried to start Firefox in Safe Mode, restarted with Add-ons Disabled and re-installed them all again. Problem is unsolved.

**Comment by DawnB2** [comment]
looks like its back for me too, what do I need to download for you to look in my system?

**Comment by inbasic** [comment]
Either TeamViewer desktop software or this Chrome extension https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp

**Comment by inbasic** [comment]
Also I need a text editor, like Nodepad++

**Comment by WhiteWolfSix** [comment]
I have TeamViewer running on my desktop.

**Comment by DawnB2** [comment]
do White Wolf first then let me know if you want to look in mine

**Comment by inbasic** [comment]
@WhiteWolfSix give me the temporary user and pass.

**Comment by WhiteWolfSix** [comment]
242 392 942
b338fi

**Comment by WhiteWolfSix** [comment]
There is test profile and dummy gmail...

**Comment by inbasic** [comment]
@DawnB2 do you have inbox.google.com redirection like @WhiteWolfSix

**Comment by WhiteWolfSix** [comment]
@inbasic sorry for you got a little lost in translation :)

**Comment by DawnB2** [comment]
no I use regular gmail.com & the delete works its just slower then it used to be

**Comment by inbasic** [comment]
Okay, v0.8.6 is out. @WhiteWolfSix your issue should have been reresolved. Please confirm.

@DawnB2 upgrade to 0.8.6 and open the options page. Go to the misc section and update the following prefs:

Ask Gmail to prevent 'inbox.google.com' redirection -> false
Faster actions (mark as read, delete, ...) -> true

Note that this only works if inbox redirection is not active on your Gmail account.

**Comment by DawnB2** [comment]
Faster Action won't stay checked. When I check it then close the options window & reopen its unchecked again, tried 3 times

**Comment by inbasic** [comment]
Open the browser error console (Ctrl + Shift + J). Disable and re-enable the extension and see if you get an error in the console or not. How about when this new option is checked?

**Comment by WhiteWolfSix** [comment]
@inbasic After upgrade everything seems to be ok. My issue is solved now.

**Comment by DawnB2** [comment]
when I disable then enable notifier I get these errors in the console:
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
1513207891154	addons.webextension.jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
When I check Fast I get
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
When I delete an email I get:
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  ExtensionUtils.jsm:505:50

**Comment by inbasic** [comment]
@DawnB2 none of these seem to be important! Can you try on a clean profile?

**Comment by DawnB2** [comment]
Clean Profile no addons but notifier

Errors:
 1513233928460	addons.webextension.jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack	WARN	Please specify whether you want browser_style or not in your browser_action options.
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDOMWindowUtils.isParentWindowMainWidgetVisible] nsPrompter.js:349
Scripts may not close windows that were not opened by script.  redirect.js:25:11
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified (unknown)
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead. (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-kA6YHvbCZc5JvqkG4a7nnqWegtw' 'strict-dynamic' 'unsafe-eval' 'unsafe-inline' https:”). Source: onsubmit attribute on INPUT element.  0
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Use of Mutation Events is deprecated. Use MutationObserver instead.  rs=AHGWq9Bnle7YTnnJoSzlEUIN3pL5qg4Jmg%20line%20113%20%3E%20eval:269:77
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.  ExtensionCommon.jsm:407
Scripts may not close windows that were not opened by script.  redirect.js:25:11
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  ExtensionUtils.jsm:505:50

**Comment by inbasic** [comment]
If you have a TeamViewer ready, I can take a look. There is no need to create a new Gmail account as I only need to check the options page.

**Comment by DawnB2** [comment]
386 093 120
6176

**Comment by inbasic** [comment]
@DawnB2 I am going to fix the non-persistency issue in the next release. Just note that when it is checked once, it switches to the fast mode although the option does not reflect this!

**Comment by DawnB2** [comment]
ok
