### ISSUE TITLE
Check for new mail?

### ISSUE THREAD

**Issue by snegostup** [inbasic/ignotifier#495]
Firefox version: 57.0.2 (64-bit)
Addon version: 0.8.6

Previously Ctrl+Click on the icon in the Firefox toolbar resulted in immediate checking for new mail. After one of the latest updates it stopped working and I can't see anything on this in the settings. How to force it to check for new mail?

**Comment by inbasic** [comment]
Right, the new FF does not allow event listeners on the toolbar and hence there is no way to support the Ctrl+Click anymore. Use the right-click menu over the toolbar for this action.
