### ISSUE TITLE
Archive doesn't work on opera.

### ISSUE THREAD

**Issue by master94ga** [inbasic/ignotifier#496]
The Archive Button doesn't work on Opera, it just mark the email as read but not archived.

**Comment by inbasic** [comment]
Can you try the latest Firefox version and see if it works or not? Both the Chrome and Opera versions will be updated to the currently released FF version soon.

**Comment by master94ga** [comment]
Doesn't work on FF too, in both browser mark the email as "Read" but not archived, it stays in the "Incoming" folder while it should disappear as always.

**Comment by master94ga** [comment]
Fixed in 0.8.9
