### ISSUE TITLE
Notifier and Google Advanced Protection

### ISSUE THREAD

**Issue by LJG5000** [inbasic/ignotifier#497]
Will Notifier- work with Google Advanced Protection? Since it  interacts with Gmail, I would guess not- however, it is a Google approved app.

Thanks,

Lowell

**Comment by somemy** [comment]
Notifier and Google Advanced Protection

**Comment by inbasic** [comment]
If your browser is logged-in I would say it should work (I haven't tried this Google Advanced Protection though). Basically, if you can open https://mail.google.com/mail/u/0/feed/atom in a browser tab without the need to sign in, the extension should be able to fetch new emails just fine.
