### ISSUE TITLE
emails now open in "all mail" instead of inbox

### ISSUE THREAD

**Issue by tomsteele1** [inbasic/ignotifier#500]
Emails opened from the pop-up notification now direct to the /#all URL for the message instead of the /#inbox

**Comment by inbasic** [comment]
It really depends on your label settings. If you have `inbox` or an empty label then they get opened with `/#inbox`

**Comment by tomsteele1** [comment]
as far as i can tell, this isn't true. the functionality changed in january, with no change in my label settings.
