### ISSUE TITLE
turning off "Enable notifications" does not stick after FF restart

### ISSUE THREAD

**Issue by noamper** [inbasic/ignotifier#501]
I like to keep "Enable notifications" off, but the setting re-enables itself with each Firefox restart. (The ability to glance at the number of unread messages in the envelope icon in the toolbar is all the notifying I need, personally.) I'm using add-on v0.9.1 with Firefox v58.0.1 (64-bit) on Windows 8.1. The behavior started after upgrading Firefox past v57, IIRC.

On the whole I love this add-on - thank you for making it! Maybe this issue is more feature than bug and I'm missing some simple config setting? All ears, of course.

**Comment by inbasic** [comment]
Have you tried the settings page? You can disable the sound notification from the settings page. I'll update the label to prevent confusion. The toolbar context is for a single session

**Comment by noamper** [comment]
Thanks, I was assuming toolbar context changes were meant to stick across sessions. Looking back, I'm afraid I can't remember for certain what form of notification had been bothering me. I did disable the sound notification in the settings page before writing up the issue; my best guess is the sound persisted and I mistakenly assumed the toolbar context item had something to do with it. In any case I am now using FF 59.02 and no longer finding anything to complain about. Thanks for having a look.
