### ISSUE TITLE
Cannot mark email as read

### ISSUE THREAD

**Issue by orschiro** [inbasic/ignotifier#506]
Dear @inbasic,

Love your extension and use it with Chrome 65.

Thanks so much for your work!

Sometimes I cannot mark emails as read. Need to manually go into Gmail to do so.

Screencast: https://youtu.be/Ga7UFl9kHxg

Any ideas what could cause the issue?

Thanks!

**Comment by inbasic** [comment]
Hello, sorry for the late reply. Do you still have the issue with the latest release?

**Comment by orschiro** [comment]
No, solved. Thank you! :-)
