### ISSUE TITLE
Alerts for single email addresses?

### ISSUE THREAD

**Issue by Buttons01** [inbasic/ignotifier#509]
Hi, apologies if I've missed something. I need desktop alerts for emails from one email address alone. Just one. Can I do this with notifier?
Thanks
Daina

**Comment by Buttons01** [comment]
Actually don't worry. I've found checker plus and figured that out. But thank you. Your product would be great if I needed more than one email highlighted.

**Comment by inbasic** [comment]
duplicate of https://github.com/inbasic/ignotifier/issues/510
