### ISSUE TITLE
Buttons in notifications doesn't work

### ISSUE THREAD

**Issue by simonbcn** [inbasic/ignotifier#513]
```
Arch Linux
GNOME Shell 3.28.2
Google Chrome 66.0.3359.139
```

Since several versions of Google Chrome (I don't know what the exact version is), the buttons in the notifications don't do anything.
Even if I click on the notification that should open a tab with the mail it works only sometimes.
The problem may not be with this extension but with GNOME Shell or Google Chrome.

**Comment by inbasic** [comment]
do you still have this issue?

**Comment by simonbcn** [comment]
I use Firefox now and it works.
