### ISSUE TITLE
[question]Open Gmail accounts when click on icon

### ISSUE THREAD

**Issue by Nemo1985** [inbasic/ignotifier#516]
Hello, I'm still using the old Gmail Watcher 2.29, I was wondering if Gmail notifier can do the same thing, now when I get a new email a pop up appears on the right lower corner of the screen, while in the tool bar when I click on the icon it opens the gmail accounts where I have unreaded emails.

Thank you in advance.

**Comment by Nemo1985** [comment]
It seems ill keep using Gmail Watcher, thank you anyway...

**Comment by inbasic** [comment]
We will have a new mode to force opening Gmail even if you have multiple accounts (as of the next release)
