### ISSUE TITLE
Options greyed out in Chrome

### ISSUE THREAD

**Issue by larrymcj** [inbasic/ignotifier#521]
I installed Notifier for Gmail on a Pixelbook and when I select "Options" from the right-click contextual menu, it's greyed out. I tried uninstalling/reinstalling...same thing. I'm trying to enable sound for new Gmail notifications.

**Comment by inbasic** [comment]
do you still have this issue?

**Comment by larrymcj** [comment]
I did until I finally just gave up and uninstalled it.

Larry
