### ISSUE TITLE
Icon in toolbar, but no notifications

### ISSUE THREAD

**Issue by jpg108** [inbasic/ignotifier#524]
I want to have notifications for multiple gmail account.
Having installed the add-on, I see the little envelope in the toolbar. But when I send an email to one of the accounts which are open in gmail, it doesn't register in the icon.

I unsuccessfuly tried it after closing all but one of the open gmail accounts, and sent an email to that one.

I dunno ... it's baffled me. I've been fiddling around with it this for quite a while, and so far got nowhere...

Thank you anyone for coming to the rescue  :)

Firefox 61.0.2; Mac [Mavericks].

**Comment by user8446** [comment]
Do you have 3rd party cookies blocked?

**Comment by inbasic** [comment]
please reopen if you want to provide more details.
