### ISSUE TITLE
[Feature Request] Add setting to prevent alerts showing on windows lock screen

### ISSUE THREAD

**Issue by tjhleeds** [inbasic/ignotifier#532]
I've noticed that alerts for new emails show even if my computer is locked. I don't want other people to be able to see the content of those alerts while I'm away from my desk. Is it possible to either change this behaviour, or add a setting to allow the user to configure it?

**Comment by inbasic** [comment]
I am not a Windows users, but since browsers use the default notification system, this should work; https://www.tenforums.com/tutorials/31116-turn-off-lock-screen-notifications-windows-10-a.html

**Comment by tjhleeds** [comment]
I already have that setting switched off, but the Notifier for Gmail chrome extension doesn't use windows notifications. It has a custom notification with options to mark emails as read, and archive them.

**Comment by inbasic** [comment]
There is a setting to remove the notification buttons in the options page. Maybe if that option is unchecked, then the default notification is used.

**Comment by tjhleeds** [comment]
I checked and you're quite right, it uses the windows notifications (which obey the windows setting) if that option is unchecked. Is it possible for the notification which does have the extra buttons to also be sensitive to the windows option, or to have a setting within the extension which controls whether or not notifications are shown on the lock screen?

**Comment by inbasic** [comment]
unfortunately not; https://developer.chrome.com/apps/notifications#type-NotificationOptions

**Comment by tjhleeds** [comment]
Ah well, thanks for your help.
