### ISSUE TITLE
Not working on Chromium 71

### ISSUE THREAD

**Issue by nitrobg** [inbasic/ignotifier#534]
The extension always returns 401 unauthorized and the icon is blue:
`GET https://mail.google.com/mail/u/0/feed/atom?rand=6937441 401     app.js:72`

Chromium on Windows, build 71.0.3576.0, downloaded from http://chromium.woolyss.com/

**Comment by inbasic** [comment]
I am not able to reproduce in "Version 72.0.3591.0 (Developer Build) (64-bit)". Can you open https://mail.google.com/mail/u/0/feed/atom?rand=6937441 in a browser tab?

**Comment by nitrobg** [comment]
It works fine on a clean profile, but it doesn't work on the current one. Disabled all other extensions, still the same.
Yes, I can open the feed address, but sometimes (I'm still trying to reproduce the exact case) it asks me to enter username and password.

**Comment by inbasic** [comment]
Please reopen if there is a way to reproduce this.
