### ISSUE TITLE
[Bug] Badge text black on Firefox 63

### ISSUE THREAD

**Issue by ThibaultVlacich** [inbasic/ignotifier#536]
The text in the badge is now black instead of white since Firefox 63.0 (I think the issue appeared after I updated).

No issue with other extensions, text is still white.

![Screenshot](https://user-images.githubusercontent.com/334940/47569775-d16e6580-d934-11e8-9735-045404563991.png)

**Comment by inbasic** [comment]
This is new in FF. Based on the background color, the text color is being decided! If you don't like the black color, make the bg color darker.
