### ISSUE TITLE
0.95 need new permission to access data for mail.google.com ?

### ISSUE THREAD

**Issue by simon129** [inbasic/ignotifier#538]
I didn't see anything in changelog about this, could you give us a insight what new feature you are working on depend on this permission.

Thanks!!

![image](https://user-images.githubusercontent.com/240547/48527682-f8caa980-e8c6-11e8-8f04-f17874da87d1.png)

**Comment by inbasic** [comment]
It is related to https://github.com/inbasic/ignotifier/blob/master/WebExtension/lib/wrapper/chrome/app.js#L181 where the extension updates the badge counter if the user marks an email as read or unread from the Gmail UI.
