### ISSUE TITLE
It doesn't mark emails as read when I archive it

### ISSUE THREAD

**Issue by simonbcn** [inbasic/ignotifier#561]
```
Operating System: Arch Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Chromium v85.0.4183.121
Notifier for Gmail v0.9.6
Plasma 
```

I have checked "_Mark message as read when archiving_" option and I have activated the `Archive` quick action from notification box. But when I press `Archive` quick action, it doesn't mark it as read.

**Comment by TheKrush** [comment]
I'm experiencing this as well.

**Comment by RobotManager** [comment]
Same problem here.
