### ISSUE TITLE
Delete button on the preview pane will randomly stop working

### ISSUE THREAD

**Issue by Shadowpheonix** [inbasic/ignotifier#564]
I am having an issue where the Delete button on the preview pane will randomly stop working.
When this occurs, the Delete button visibly reacts as it should, but the message does not advance to the next one and the message is not deleted from my inbox.
Once this occurs, I am unable to delete any messages using the preview pane until I either restart Chrome, or go into my inbox and clear all unread messages (after which, Notifier will then allow me to delete any new messages I get until the issue re-occurs).
I have noticed this occurs most frequently when I get multiple messages from the same sender, although that is not the only time it occurs.
I am using version 0.9.6 in Google Chrome.

**Comment by agentlogic** [comment]
I can confirm this happens on Firefox as well.

Firefox version 89.0.1
Add-on version: 1.0.1

**Comment by agentlogic** [comment]
This is possibly related to #577 which has more details about the errors that show on the console.

A quick fix is to disable the add-on and re-enable it, instead of having to restart the browser.

**Comment by inbasic** [comment]
Thanks for the report. Should be fixed by 1.0.2 release. Please reopen if not.

**Comment by agentlogic** [comment]
@inbasic Thank you so much for the quick fix! I can confirm it is working well.

Thank you for all your hard work on this extension, I've been a long time user and it has helped my productivity greatly!
