### ISSUE TITLE
Preview/full-content mode is cut off

### ISSUE THREAD

**Issue by capturedghosts** [inbasic/ignotifier#568]
After updating to Chrome 91.0.4472.77, the preview area in full-content mode is squished horizontally (it's exactly 50 pixels high) despite my toolbar panel width and height being set to 750x600.

![Untitled](https://user-images.githubusercontent.com/2073512/119687683-66031200-be15-11eb-9f0f-db6eae5c09aa.png)

**Comment by AlexApps99** [comment]
I can reproduce
![image](https://user-images.githubusercontent.com/30854646/119747463-e6457800-bee6-11eb-96fe-9aaaefb29a9b.png)

**Comment by capturedghosts** [comment]
@inbasic thanks for the swift fix!
