### ISSUE TITLE
Can no longer delete emails

### ISSUE THREAD

**Issue by Shadoefax** [inbasic/ignotifier#569]
Version 0.9.7 auto-installed today. I can no longer delete emails from the popup (cursor just spins) and I have to manually delete them through the Gmail webpage. Reverted back to v0.9.5, turned off auto-update and all is working again.

**Comment by Avrution** [comment]
Not just deleting, cannot mark as read or archive, etc.

**Comment by inbasic** [comment]
What is your browser version? OS? Also can you open the basic HTML view? https://mail.google.com/mail/u/0/h/

**Comment by Shadoefax** [comment]
Notifier for Gmail™ 0.9.9
Fx 56.0.2 (64-bit) - (Highest pre-Quantum version)
Windows 10 Home v2004 (latest version)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0

[](https://mail.google.com/mail/u/0/h/) opens just fine.

Cannot delete emails or "Mark as read". Cursor just spins.
