### ISSUE TITLE
Preview mode got broken in 0.9.7 in Mozilla Firefox in GMail basic HTML view

### ISSUE THREAD

**Issue by lebedev** [inbasic/ignotifier#570]
Hi!
In version 0.9.7 preview mode got broken for me in Mozilla Firefox in GMail basic HTML view.
It shown a spinner indefinitely:
![image](https://user-images.githubusercontent.com/5000549/120000468-a8cf1080-bff4-11eb-980b-fba6dcf7a463.png)
And shows the following error:
![image](https://user-images.githubusercontent.com/5000549/120000687-e59b0780-bff4-11eb-8c91-218ecd07c5ac.png)
With standard view it works as intended. It happens only if I set `basic HTML` as default view. For that, I clicked on this link first
![image](https://user-images.githubusercontent.com/5000549/120001691-dbc5d400-bff5-11eb-801f-76b38b45dc86.png)
And then on
![image](https://user-images.githubusercontent.com/5000549/120001774-f304c180-bff5-11eb-9060-b3b62cb42396.png)

Preview mode with `basic HTML` works in 0.9.6, so this seems like a regression.

Is there anything else I can help with?

**Comment by inbasic** [comment]
Thanks for the report. Should be fixed by the 0.9.8 release

**Comment by lebedev** [comment]
I can confirm that it's fixed in 0.9.8. Thanks a lot!
