### ISSUE TITLE
"Mark All as Read" button not showing anymore

### ISSUE THREAD

**Issue by chescos** [inbasic/ignotifier#571]
Has the `Mark All as Read` button been removed? I've been using this awesome extension for over a year now and always used the `Mark All as Read` button to mark all unread emails as read. But suddenly, the button disappeared. Has it been removed or is something wrong with my installation?

**Comment by inbasic** [comment]
No, the UI is not changed! Can you share a screenshot

**Comment by br4nch** [comment]
Same question. Here is the screenshot for your reference
![image](https://user-images.githubusercontent.com/20967549/120061818-217fac80-c089-11eb-80a7-68533a9d19db.png)

**Comment by inbasic** [comment]
Thanks for the report. Should be gone by 0.9.9 release.

**Comment by br4nch** [comment]
Thank you for all the hard work! I have been using it for almost 5 years now. It's one of my favorite extensions.
