### ISSUE TITLE
Opens gmail tab when resuming from hibernation

### ISSUE THREAD

**Issue by ktmn** [inbasic/ignotifier#575]
Every time I resume from hibernation (Win10) it opens Gmail in a new tab (Firefox). My network isn't even connected by then so it's just an error page. 

Is this supposed to happen? Am I missing an option somewhere?

**Comment by inbasic** [comment]
There are many factors involving. So I can prepare a test version to debug the issue if you are willing to give it a try?

**Comment by ktmn** [comment]
Sure

**Comment by inbasic** [comment]
1. Disable the AMO version of the extension
2. Download [v2.zip](https://github.com/inbasic/ignotifier/files/6759516/v2.zip) in a local directory
3. Open "about:debugging#/runtime/this-firefox" in a browser tab
4. Point "Load Temp Add-on..." to the v2.zip
5. Press the "Inspect" button

Every time the extension opens a new tab, you will get two logs in the "Console" tab. Do a hibernate and report the logs if the extension opens a Gmail tab.

**Comment by ktmn** [comment]
Couldn't reproduce with that version.
