### ISSUE TITLE
Delete sometimes doesn't work (after a long session?)

### ISSUE THREAD

**Issue by seaders** [inbasic/ignotifier#577]
Sometimes, after a new email comes in, if I try to delete it, it tries for a second, and then does nothing.  The popup just stays on screen.

In the browser console, these errors show,

    [Exception... "Conduits:RuntimeMessage: message reply cannot be cloned."  nsresult: "0x80004005 (DataCloneError)"  location: "<unknown>"  data: no]

    ConduitsParent.jsm:297

        _raceResponses resource://gre/modules/ConduitsParent.jsm:297
        
    Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.

    index.js:310

        action moz-extension://1926230a-49a4-6443-a66f-dbf1980b62d1/data/popup/index.js:310

---

As an additional thing (unrelated to the main issue), I've noticed this error on closing of the extension popup window,

    sendRemoveListener on closed conduit jid0-GjwrPchS3Ugt7xydvqVK4DQk8Ls@jetpack.412318062467

    ConduitsChild.jsm:108

          _send resource://gre/modules/ConduitsChild.jsm:108
          _send self-hosted:1282
          removeListener resource://gre/modules/ExtensionChild.jsm:663
          removeListener resource://gre/modules/ExtensionChild.jsm:886
          onChanged chrome://extensions/content/child/ext-storage.js:332
          removeListener resource://gre/modules/ExtensionCommon.jsm:2528
          revoke resource://gre/modules/ExtensionCommon.jsm:2550
          close resource://gre/modules/ExtensionCommon.jsm:2555
          unload resource://gre/modules/ExtensionCommon.jsm:917
          unload resource://gre/modules/ExtensionPageChild.jsm:261
          unload resource://gre/modules/ExtensionPageChild.jsm:298
          destroyExtensionContext resource://gre/modules/ExtensionPageChild.jsm:482
          observe resource://gre/modules/ExtensionPageChild.jsm:395

**Comment by inbasic** [comment]
Thanks for the report. Should be fixed by 1.0.2 release.
