### ISSUE TITLE
Remove google redirecting url

### ISSUE THREAD

**Issue by N1N74** [inbasic/ignotifier#578]
Links via gmail displays as the correct url but links via the extension are google redirect links. Seems like it's possible to avoid this.

**Comment by N1N74** [comment]
This was fixed but seems to be occurring again.

**Comment by N1N74** [comment]
Issue seems to be happening again

**Comment by N1N74** [comment]
Hello, we may need to re-open this issue. lol

**Comment by inbasic** [comment]
It is not happening for me. What is the URL format?

```
https://www.google.com/url?hl=en&q=[actual_address]
```

**Comment by N1N74** [comment]
Ah wait, sorry, my bad. It's working. ^^
