### ISSUE TITLE
Beta/Development version is extremely slow at detecting new emails

### ISSUE THREAD

**Issue by LoganDark** [inbasic/ignotifier#581]
I used to receive notifications within seconds of each email. The development version takes 5 minutes or more to check for emails (recently it took 9). What gives? Why can't I configure this?

**Comment by inbasic** [comment]
You can configure the period on the options page (The "Period (in minutes)" option on the notification section). However, currently, it only takes effect after the extension restart. On the next release, this pref is effective after the change without the restart required.

**Comment by LoganDark** [comment]
> You can configure the period on the options page (The "Period (in minutes)" option on the notification section). However, currently, it only takes effect after the extension restart. On the next release, this pref is effective after the change without the restart required.

Oh, I didn't know that option existed. The label and text box are so far apart I didn't notice. Sorry
