### ISSUE TITLE
Cannot get "at" from the base page

### ISSUE THREAD

**Issue by DeaD3R** [inbasic/ignotifier#590]
![gm](https://user-images.githubusercontent.com/16120515/136653752-533228dc-9d65-42f9-8183-4d00ca262843.png)

I get this when trying any action from the extension window: delete, mark as read, archive. Always get this notification and the action doesn't happen.

Started yesterday, reinstalling extension doesn't fix it.

On different profile it works as it should, so some setting from my profile possibly started affecting it yesterday. Any way to troubleshoot?

Firefox 93.0, Windows 10

**Comment by AlexSus** [comment]
Same story, starts 2 days ago

**Comment by gakun17** [comment]
Same here, Firefox 93.0 (64-bits), Windows 10 20H2.

**Comment by juanrafaelgomez** [comment]
Same here Firefox 94.0b4 (64-bit), Windows Version 10.0.19042.1237

**Comment by adrianiepure** [comment]
Same here on Firefox 93.0 (64-bit), Windows 10 Version 21H1 (OS Build 19043.1266)

**Comment by Avrution** [comment]
Same issue on Waterfox G3

**Comment by YoshkaPundrik** [comment]
Same. Firefox 90.0.2 (64 bit), Win10 21H1, Extension v1.0.4

**Comment by tam8** [comment]
I was able to use it temporarily when I changed my Gmail account,
I can no longer use that account.

**Comment by m5g** [comment]
Same here

**Comment by KarinaAnoshko** [comment]
I ran into the same issue.
Notifier version 1.0.4
Firefox version: 93.0
Ubuntu 18.04 and Ubuntu 16.04.

**Comment by DeaD3R** [comment]
I'm closing this since it seems to be fixed
