### ISSUE TITLE
Possible to still play email sounds with media.autoplay.default set to anything except 0?

### ISSUE THREAD

**Issue by Avrution** [inbasic/ignotifier#598]
Finally had enough of all the auto play videos and went about disabling them in about:config.  Noticed my email notifications stopped playing sound.

Determined the key "media.autoplay.default" being set to anything except 0 caused the problem.  Hard to decide between annoying autoplaying videos and no longer being notified about new emails when my laptop is closed.  

Is there a workaround by chance?

This is in Firefox/Waterfox

**Comment by Imold** [comment]
Open the settings page, then open "Page Info"( Ctrl+i ), go to the Permissions tab, find "Autoplay" uncheck "Use Default", and select "Allow Audio and Video".
