### ISSUE TITLE
dark mode please

### ISSUE THREAD

**Issue by ghost** [inbasic/ignotifier#601]
make it possible to get dark mode or even costomisable . themes for extension

**Comment by lukaszpolowczyk** [comment]
Also please. Best to have it match your system settings.

**Comment by leic4u** [comment]
+1 please

**Comment by Avrution** [comment]
Dark mode toggle might be better moved to the settings page, not on the main email window.  

The placement kind of destroys years of muscle memory and I doubt people will be toggling it per email they check.

**Comment by look997** [comment]
@Avrution @sovalyeler It is better that it adapts to the system settings, i.e. the extension must have the "auto" option, and you can change it in the system.

**Comment by inbasic** [comment]
The button's inability to follow the system theme is due to its experimental nature. As an alternative, I can implement a dropdown menu on the options page. When "Auto" mode is selected, it will hide the panel's button.
