### ISSUE TITLE
Can't mark second gmail account emails as read

### ISSUE THREAD

**Issue by Jeytav** [inbasic/ignotifier#617]
Up until a few days ago I have been able to mark all my emails on both my gmails accounts as read, but for some reason I can't do that anymore, my main email still works as intended, but my secondary wont let me mark as read and it doesn't even load the preview of the mail anymore
 
I have changed the settings of  my secondary email to match the one from my main email but nothing seems to make it work.

![image](https://github.com/inbasic/ignotifier/assets/13339208/c0cdf64b-d428-45fd-8d64-2f7504bdd855)

**Comment by inbasic** [comment]
Can you open the feed for the secod account:
https://mail.google.com/mail/u/1/feed/atom

How about basic view
https://mail.google.com/mail/u/1/h/

**Comment by Jeytav** [comment]
huh interesting, the feed worked fine, with the basic view I had to first decline the new gmail format thingy and then authorize a login and now it works, soo thanks I guess :)
