### ISSUE TITLE
Toolbar Button context menu items missing after restart (Firefox)

### ISSUE THREAD

**Issue by Imold** [inbasic/ignotifier#620]
On Firefox "Logged-in accounts", "Disable all notifications", "Enable notifications (session)", "Compose an email", "Refresh"', and "Open FAQs" are only added to the Toolbar Button context menu when the addon is first installed, and not after opening the browser with the addon already installed.

**Comment by inbasic** [comment]
I am updating the FF version to 1.1.2. Please reopen if you still have the issue on this new version.

**Comment by hasezoey** [comment]
i think i had also run into this issue, at first thinking it was a firefox issue (and creating https://bugzilla.mozilla.org/show_bug.cgi?id=1866274), but after reverting firefox noticing it also happened on the old version of firefox (but a extension updated tab opened)

how long does it usually take for a version to be up on the firefox addons store?

**Comment by inbasic** [comment]
Firefox review is very slow! It is pretty hard to fix FF-related bugs this way.

**Comment by Imold** [comment]
You could publish the .xpi here. There hasn't been a new release added sense 2017.
