### ISSUE TITLE
Custom options when right click

### ISSUE THREAD

**Issue by barbarolucente** [inbasic/ignotifier#621]
We used to have some custom options right clicking the extension icon, like opening a specific account.
Any plan to have it back?

**Comment by 4javier** [comment]
I second this one.
In particular the option to open directly anyone of the bound accounts and the one to issue an explicit poll for new email.
Useful when you know a verification message has been sent to one of your inboxes.

**Comment by neonVoice** [comment]
I used this context menu to temporarily disable notification, but now this menu is gone. I'm on Firefox.

**Comment by btamburrino** [comment]
I wouldn't be surprised if Firefox v120 changed the way right click options for an extension were done - I've noticed several of my extensions that had a right-click menu lost all of their menu items this week.

I used the right click menu to manually refresh my inboxes.

The double whammy of Gmail changing up how you can access it and Firefox seemingly changing up how addons are made is making the end of 2023 so much fun for this extension, I'm sure...

**Comment by 4javier** [comment]
It's still feasible for sure, anyway.
I got at least two extensions showing custom context menus (Downthemall and SimpleTranslate).
I got no experience with extensions, but at a first search it doesn't look like a feature too hard to be implemented.

**Comment by inbasic** [comment]
This is related to 1.1.1 release. I've already submitted a fixed. Though the extension is still under review.
