### ISSUE TITLE
Sound Alerts No Longer Works in v1.1.1 (Firefox)

### ISSUE THREAD

**Issue by amiga-500** [inbasic/ignotifier#623]
This problem occurred immediately after upgrading to v1.1.1.
Downgrading back to 1.0.5 fixed the problem.

v1.1.1 also causes pop up alerts to keep re-showing.
You also cant click the "Play" button to test selected user sounds.

Seems v1.1.1 was put out without testing.

**Comment by Avrution** [comment]
Had the same issue with the new update - went back to the old plugin just to have sounds for now.

**Comment by inbasic** [comment]
What is your Firefox version?

**Comment by amiga-500** [comment]
Latest Firefox

**Comment by amiga-500** [comment]
> Had the same issue with the new update - went back to the old plugin just to have sounds for now.

Thanks for the heads up...Downgrading fixed my problem (sound works again).

**Comment by Avrution** [comment]
1.1.3.1 finally went live and it still has the issue

**Comment by inbasic** [comment]
@Avrution can you reproduce on a clean profile?

**Comment by inbasic** [comment]
Try this developer version and let me know if the sound issue is fixed or not

[extension.zip](https://github.com/inbasic/ignotifier/files/13484681/extension.zip)

To install click on the "Load Temporary Add-on" on this page:

about:debugging#/runtime/this-firefox

**Comment by Avrution** [comment]
> @Avrution can you reproduce on a clean profile?

Worked fine on a new profile, so wiped the settings file and everything it working normally sound wise.  Having another issue, but will make a new post

**Comment by Avrution** [comment]
> Try this developer version and let me know if the sound issue is fixed or not
> 
> [extension.zip](https://github.com/inbasic/ignotifier/files/13484681/extension.zip)
> 
> To install click on the "Load Temporary Add-on" on this page:
> 
> about:debugging#/runtime/this-firefox

New issue - while the sound works for the default, as soon as you put anything in the custom spots the sound breaks for everything.  Not even a sound file, just putting in an email address or any text into the field such as "test"

**Comment by ivanbauer** [comment]
Same issue on Chrome version 1.1.3.
