### ISSUE TITLE
Accounts not staying in the right click menu

### ISSUE THREAD

**Issue by sv110mhh** [inbasic/ignotifier#626]
Have used this for years.

Right now... none of the accounts I use are staying in the menu so I can right click on the icon in the toolbar and check each account.

![image](https://github.com/inbasic/ignotifier/assets/152073964/5c534bf8-b81f-4de6-808d-cfdce684bc0c)

Started day before yesterday after latest update.

**Comment by Avrution** [comment]
It seems the latest update removed all of the options

**Comment by sv110mhh** [comment]
> It seems the latest update removed all of the options

Any way to revert to a previous update?

**Comment by inbasic** [comment]
Should have been fixed by the 1.1.3 release.
