### ISSUE TITLE
FF Extension icon showing in blue

### ISSUE THREAD

**Issue by AlanOsta** [inbasic/ignotifier#630]
Since the recent update the FF extension icon is showing in blue despite adding the cookies exception on FF settings.
I followed the guides on the "Details" section of the extension but the issue persist.
When I click on the blue icon it goes to Gmail Inbox for the default account

Thanks for the great job.

**Comment by Archer-Dante** [comment]
Same here.
I looks like the extention worked for a 1 day after fix-update, but soon it get blue forever and not checking emails anymore, just working like button-link to gmail and thats it

**Comment by Archer-Dante** [comment]
Since clearing whole profile is a bad way for me i've found this as solution:
delete cert_**override.txt** from _C:\Users\*user*\AppData\Roaming\Mozilla\Firefox\Profiles\*profile-name*_
Then relogin into gmail and that's it

**Comment by AlanOsta** [comment]
@Archer-Dante thanks a lot for your input, I've tried your solution without luck for me.
I didn't had the time to troubleshoot with @inbasic suggestions, if I found something I will post it here.

Once again, thank you both for your advises.
Alan.
