### ISSUE TITLE
Left clicking link no longer functions (Waterfox / Firefox ESR 102)

### ISSUE THREAD

**Issue by Avrution** [inbasic/ignotifier#636]
Everything is working great in the new version, but I cannot left click on any links.  Middle clicking opens links in a background tab, right clicking opens the link context menu, left click - no response.

Created a new profile and it has the same issue.

**Comment by IanDaBest** [comment]
This happens to me too

**Comment by frshhh** [comment]
Same
Firefox 120.0.1
Notifier 1.1.5

**Comment by Archer-Dante** [comment]
Same

**Comment by silverlays** [comment]
Same here for Opera and Chrome versions
