### ISSUE TITLE
Clicking on link doesnt automatically create new tab

### ISSUE THREAD

**Issue by TheBabu** [inbasic/ignotifier#640]
When clicking on a link in the pop window, clicking on a link doesn't automatically spawn a new tab. 

This was the behavior originally, but somehow changed in a new update perhaps. Now the only way to click links is to right click and hit open new tab, which is clunky.

**Comment by inbasic** [comment]
What is the browser?

**Comment by TheBabu** [comment]
Google chrome version 121.0.6167.140

**Comment by TheBabu** [comment]
Version 1.1.6 of the extension has fixed it, closing.
