### ISSUE TITLE
Firefox 130.0 (Linux): no sound

### ISSUE THREAD

**Issue by svarshavchik** [inbasic/ignotifier#680]
After updating to Firefox 130.0 new mail notification popups gone silent. They still pop up, but there's no sound.

I tried picking different sounds, no difference. Possibly related: the "Play" button on the preference page, next to the dropdown list which plays the selected sound alert, does not respond to clicks in any way, no visual feedback.

Sound, generally, is working normally, otherwise.

**Comment by inbasic** [comment]
What is your distribution?

**Comment by svarshavchik** [comment]
Fedora 40, XFCE spin.

**Comment by inbasic** [comment]
It seems like FF on Linux cannot play `*.ogg` anymore. So I switched sound files to `*.mp4`
