### ISSUE TITLE
Notification sound disappeared

### ISSUE THREAD

**Issue by HowlinnWolf** [inbasic/ignotifier#681]
Last couple of days new emails come with pop ups but with no sound.

I was actively using "Turn notifications off for..." feature to turn sound off for a couple hours or minutes lately. Was manually clicking "Enable notifications (session)" sometimes. But at some point sound just didn't come back. Can't tell if it's a problem on my end or on add-on's.

I'm using Mozilla Firefox on Windows 11, btw. In case I somehow muted those notifications, but not the browser itself?

**Comment by inbasic** [comment]
Use the options page to use this custom MP4 sound 
https://github.com/inbasic/ignotifier/raw/master/v3.classic/data/sounds/0.mp4

Ref:
https://github.com/inbasic/ignotifier/issues/680

**Comment by HowlinnWolf** [comment]
Yep, it works now.
