### ISSUE TITLE
FEAT: Move or hide Dark Mode button in Settings

### ISSUE THREAD

**Issue by sfsam** [inbasic/ignotifier#691]
Most of the buttons in the toolbar at the bottom of the popup pertain to operations on email. This makes sense since that is the point of the extension. The one that sticks out is the dark mode button. It seems like that toggle should either be in the Settings page or there should be an option in Settings to hide the button. Either way, it doesn't seem to functionally belong in the toolbar.

**Comment by inbasic** [comment]
For certain emails, users may need to switch to light mode for better readability. That's why I added a button on the popup interface to toggle it. However, if you select the system theme for the popup on the options page, this button will be hidden.
