### ISSUE TITLE
Separate sounds for accounts

### ISSUE THREAD

**Issue by Dudes1** [inbasic/ignotifier#9]
Can we have the option to assign each account their own sound?  In X-notifier I was able to do so via the about:config page.

**Comment by inbasic** [comment]
The new version will allow you to define filters for sound notifications;

You can try the beta version now:
https://github.com/inbasic/ignotifier/blob/beta/builds/packed/firefox.xpi?raw=true
Download the XPI and load it in about:Debugging tab
